/**
 * queryOptions configs contains Values to be displayed while making a search
 * to NCBI DB
 */
export const QueryOptions = {
  drugs: [
    '(-)-Blebbistatin',
    '(-)-Huperzine A (HupA)',
    '(-)-JQ1',
    '(-)-MK 801 Maleate',
    '(-)-Parthenolide',
    '(-)-p-Bromotetramisole Oxalate',
    '(-)-Tetramisole',
    '(+)-Bicuculline',
    '(+)-JQ1',
    '(+)-Matrine',
    '(+)-Usniacin',
    '(+,-)-Octopamine HCl',
    '(6-)ε-​Aminocaproic acid',
    '(R)-baclofen',
    '(R)-Nepicastat HCl',
    '(S)-10-Hydroxycamptothecin',
    '(s)-CR8',
    '(S)-crizotinib',
    '(Z)-4-Hydroxytamoxifen',
    '10058-F4',
    '10-Deacetylbaccatin-III',
    '17-AAG',
    '17-DMAG (Alvespimycin) HCl',
    '1-Azakenpaullone',
    '1-Hexadecanol',
    '20-Hydroxyecdysone',
    '2-deoxyglucose',
    '2-Methoxyestradiol (2-MeOE2)',
    '2-Thiouracil',
    '3-deazaneplanocin A (DZNeP) HCl',
    '3-Indolebutyric acid (IBA)',
    '3-Methyladenine (3-MA)',
    '4-Aminohippuric Acid',
    '4E1RCat',
    '4EGI-1',
    '4-Methylumbelliferone (4-MU)',
    '4SC-202',
    '4μ8C',
    '5-Aminolevulinic acid HCl',
    '5-DFUR',
    '5-FU',
    '5-hydroxymethyl Tolterodine (PNU 200577, 5-HMT, 5-HM)',
    '5-hydroxytryptophan (5-HTP)',
    '5z-7-oxozeaenol',
    '6H05',
    '7-Aminocephalosporanic acid',
    'A 769662',
    'A-1210477',
    'A-205804',
    'A-438079 HCl',
    'A443654',
    'A66',
    'A-674563',
    'A-769662',
    'A-803467',
    'A922500',
    'A-966492',
    'Abacavir sulfate',
    'Abarelix Acetate',
    'Abemaciclib',
    'Abiraterone',
    'Abiraterone Acetate',
    'Abscisic Acid (Dormin)',
    'ABT-199 (GDC-0199)',
    'ABT-263',
    'ABT-702',
    'ABT-737',
    'ABT-751',
    'AC220',
    'AC480 (BMS-599626)',
    'Acarbose',
    'Acebutolol HCl',
    'Acemetacin',
    'Acesulfame Potassium',
    'Acetanilide',
    'Acetylcholine Chloride',
    'Acetylcysteine',
    'Aciclovir',
    'Acipimox',
    'Acitretin',
    'Aclidinium Bromide',
    'Adapalene',
    'Adefovir Dipivoxil',
    'Adenine',
    'Adenine HCl',
    'Adenine sulfate',
    'Adenosine',
    'Adiphenine HCl',
    'AdipoRon',
    'ADL5859 HCl',
    'Adrenalone HCl',
    'ADX-47273',
    'AEBSF HCl',
    'AEE788 (NVP-AEE788)',
    'Afatinib',
    'Afatinib (BIBW2992)',
    'Afatinib (BIBW2992) Dimaleate',
    'Afuresertib (GSK2110183)',
    'AG1024',
    'AG-1024',
    'AG-14361',
    'AG1478',
    'AG-1478 (Tyrphostin AG-1478)',
    'AG-18',
    'AG-490 (Tyrphostin B42)',
    'AG-F-89549',
    'AGI-5198',
    'AGI-6780',
    'AGK2',
    'Agomelatine',
    'AICAR (Acadesine)',
    'Albendazole',
    'Albendazole Oxide',
    'Alendronate',
    'Alfacalcidol',
    'Alfuzosin HCl',
    'Alibendol',
    'Alisertib',
    'Aliskiren Hemifumarate',
    'Alizapride HCl',
    'Alizarin',
    'Allopurinol',
    'Allopurinol Sodium',
    'Allylthiourea',
    'Almorexant HCl',
    'Almotriptan Malate',
    'Aloe-emodin',
    'Alogliptin',
    'Aloin',
    'Aloperine',
    'Aloxistatin',
    'Alpelisib',
    'Alprostadil',
    'Altrenogest',
    'Altretamine',
    'Alvelestat (AZD9668)',
    'Alverine Citrate',
    'Alvocidib',
    'ALW-II-38-3',
    'ALW-II-49-7',
    'AM1241',
    'AM251',
    'Amantadine HCl',
    'Ambrisentan',
    'Ambroxol HCl',
    'Amfebutamone (Bupropion) HCl',
    'Amfenac Sodium Monohydrate',
    'AMG-208',
    'AMG-458',
    'AMG-517',
    'AMG-900',
    'Amidopyrine',
    'Amifostine',
    'Amikacin disulfate',
    'Amikacin hydrate',
    'Amiloride HCl',
    'Amiloride HCl dihydrate',
    'Aminoglutethimide',
    'Aminophylline',
    'Aminothiazole',
    'Amiodarone HCl',
    'Amisulpride',
    'Amitriptyline HCl',
    'Amlodipine',
    'Amlodipine Besylate',
    'Ammonium Glycyrrhizinate',
    'Amonafide',
    'Amorolfine HCl',
    'Amoxapine',
    'Amoxicillin',
    'Amoxicillin Sodium',
    'Amphotericin B',
    'Ampicillin sodium',
    'Ampicillin Trihydrate',
    'Ampiroxicam',
    'Amprenavir',
    'Amprolium HCl',
    'Amuvatinib',
    'Amuvatinib (MP-470)',
    'ANA-12',
    'Anacardic acid',
    'Anacetrapib (MK-0859)',
    'Anagrelide HCl',
    'Anastrozole',
    'Andarine',
    'Andrographolide',
    'Angiotensin Acetate',
    'Anidulafungin (LY303366)',
    'Aniracetam',
    'Anisomycin',
    'Antazoline HCl',
    'Antipyrine',
    'AP26113',
    'Apatinib',
    'Apigenin',
    'Apixaban',
    'Apocynin',
    'Apoptosis Activator 2',
    'Apramycin Sulfate',
    'Apremilast (CC-10004)',
    'Aprepitant',
    'AR-42',
    'AR-A014418',
    'Arbidol HCl',
    'Arbutin',
    'Arecoline',
    'Argatroban',
    'Argireline Acetate',
    'Argpressin Acetate',
    'Aripiprazole',
    'ARN-509',
    'ARQ 621',
    'Artemether',
    'Artemisinin',
    'Artesunate',
    'Articaine HCl',
    'AS-252424',
    'AS601245',
    'AS-604850',
    'AS605240',
    'AS-605240',
    'Asaraldehyde',
    'Ascomycin (FK520)',
    'Asenapine',
    'Asiatic Acid',
    'ASP3026',
    'Aspartame',
    'Aspirin',
    'AST1306',
    'AST-1306',
    'Astragaloside A',
    'AT101',
    'AT13148',
    'AT7519',
    'AT-7519',
    'AT7519 HCl',
    'AT7867',
    'AT9283',
    'Ataluren (PTC124)',
    'Atazanavir Sulfate',
    'Atglistatin',
    'Atomoxetine HCl',
    'Atorvastatin Calcium',
    'Atosiban Acetate',
    'Atovaquone',
    'ATP',
    'Atracurium Besylate',
    'Atropine',
    'Aurora A Inhibitor I',
    'Avagacestat (BMS-708163)',
    'Avanafil',
    'Avasimibe',
    'Aviptadil Acetate',
    'Avobenzone',
    'AX20017',
    'Axitinib',
    'AZ 20',
    'AZ 3146',
    'AZ 5104',
    'AZ 628',
    'AZ 960',
    'AZ191',
    'AZ20',
    'AZ-628',
    'Azacitidine',
    'Azacyclonol',
    'Azaguanine-8',
    'Azaperone',
    'Azasetron HCl',
    'Azatadine dimaleate',
    'Azathioprine',
    'AZD 5438',
    'AZD1080',
    'AZD1208',
    'AZD1480',
    'AZD-1480',
    'AZD1981',
    'AZD2014',
    'AZD2461',
    'AZD2858',
    'AZD2932',
    'AZD3463',
    'AZD3514',
    'AZD3839',
    'AZD4547',
    'AZD5363',
    'AZD5438',
    'AZD6482',
    'AZD-6482',
    'AZD7545',
    'AZD7762',
    'AZD8055',
    'AZD8330',
    'AZD8931 (Sapitinib)',
    'AZD9291',
    'Azelastine HCl',
    'Azelnidipine',
    'Azilsartan',
    'Azilsartan Medoxomil',
    'Azithromycin',
    'Azithromycin Dihydrate',
    'Azlocillin sodium salt',
    'Azomycin',
    'Aztreonam',
    'Bacitracin',
    'Bacitracin Zinc',
    'BAF312 (Siponimod)',
    'Bafetinib (INNO-406)',
    'Baicalein',
    'Baicalin',
    'Balofloxacin',
    'BAM7',
    'Bambuterol HCl',
    'b-AP15',
    'BAPTA-AM',
    'Barasertib',
    'Bardoxolone Methyl',
    'Baricitinib',
    'Baricitinib (LY3009104, INCB028050)',
    'Batimastat (BB-94)',
    'BAY 11-7082',
    'Bay 11-7085',
    'BAY 80-6946 (Copanlisib)',
    'BAY 87-2243',
    'BAY-11-7082',
    'BAY61-3606',
    'Bazedoxifene HCl',
    'Beclomethasone dipropionate',
    'Belinostat',
    'Belnacasan (VX-765)',
    'Bemegride',
    'Benazepril HCl',
    'Bendamustine HCl',
    'Benidipine HCl',
    'Benserazide HCl',
    'Benzbromarone',
    'Benzethonium Chloride',
    'Benzocaine',
    'Benzoic Acid',
    'Benztropine mesylate',
    'Benzydamine HCl',
    'Bepotastine Besilate',
    'Berberine HCl',
    'Bergapten',
    'Bergenin',
    'Besifloxacin HCl',
    'Bestatin',
    'Beta Carotene',
    'beta-Amyloid (1-42) human',
    'Betahistine 2HCl',
    'Beta-Lapachone',
    'Betamethasone',
    'Betamethasone Dipropionate',
    'Betamethasone Valerate',
    'Betamipron',
    'Betaxolol',
    'Betaxolol HCl',
    'Bethanechol chloride',
    'Betulinic acid',
    'Bexarotene',
    'BEZ235',
    'BEZ235 (NVP-BEZ235, Dactolisib)',
    'Bezafibrate',
    'BG45',
    'BGJ398',
    'BGJ398 (NVP-BGJ398)',
    'BI 2536',
    'BI-2536',
    'BI-847325',
    'Biapenem',
    'BIBR 1532',
    'Bicalutamide',
    'BI-D1870',
    'Bifonazole',
    'BIIB021',
    'Bikinin',
    'Bilobalide',
    'Bimatoprost',
    'Bindarit',
    'Binimetinib (MEK162, ARRY-162, ARRY-438162)',
    'BIO',
    'Biochanin A',
    'Biotin (Vitamin B7)',
    'Birinapant',
    'Bisacodyl',
    'Bismuth Subcitrate Potassium',
    'Bismuth Subsalicylate',
    'Bisoprolol fumarate',
    'Bivalirudin Trifluoroacetate',
    'BIX 01294',
    'BIX 02188',
    'BIX 02189',
    'BIX 02565',
    'BIX-01294',
    'BIX02188',
    'BKM120 (NVP-BKM120, Buparlisib)',
    'Blasticidin S HCl',
    'Bleomycin Sulfate',
    'Blonanserin',
    'BLZ945',
    'BMH-21',
    'BML-190',
    'BMS 777607',
    'BMS-265246',
    'BMS345541',
    'BMS-345541',
    'BMS-378806',
    'BMS509744',
    'BMS-536924',
    'BMS-707035',
    'BMS-754807',
    'BMS-777607',
    'BMS-794833',
    'BMS-833923',
    'BMX-IN-1',
    'BMY 7378',
    'Bohemine',
    'Bortezomib',
    'Bortezomib (PS-341)',
    'Bosentan',
    'Bosentan Hydrate',
    'Bosutinib',
    'BPTES',
    'BQU57',
    'BRD4770',
    'BRD73954',
    'BRD7552',
    'Brefeldin A',
    'Brimonidine Tartrate',
    'Brinzolamide',
    'Brivanib',
    'Brivanib Alaninate (BMS-582664)',
    'BRL-15572',
    'BRL-54443',
    'Bromfenac Sodium',
    'Bromhexine HCl',
    'Bromopyruvic acid',
    'Bromosporine',
    'Brompheniramine hydrogen maleate',
    'Broxyquinoline',
    'Bryostatin 1',
    'BS-181',
    'BS-181 HCl',
    'BTB06584',
    'BTZ043 Racemate',
    'Buclizine HCl',
    'Budesonide',
    'Bufexamac',
    'Buflomedil HCl',
    'Bumetanide',
    'Buparlisib',
    'Bupivacaine HCl',
    'Buspirone HCl',
    'Busulfan',
    'Butein',
    'Butenafine HCl',
    'Butoconazole nitrate',
    'BV-6',
    'BX795',
    'BX-795',
    'BX-912',
    'C646',
    'Cabazitaxel',
    'Cabotegravir (GSK744, GSK1265744)',
    'Cabozantinib',
    'Cabozantinib (XL184, BMS-907351)',
    'Cabozantinib malate (XL184)',
    'Caffeic Acid',
    'Caffeic Acid Phenethyl Ester',
    'CAL-101',
    'CAL-101 (Idelalisib, GS-1101)',
    'Calcifediol',
    'Calcitriol',
    'Calcium Levofolinate',
    'Calpeptin',
    'Camostat Mesilate',
    'Camptothecin',
    'Canagliflozin',
    'Candesartan',
    'Candesartan Cilexetil',
    'Canertinib',
    'Capecitabine',
    'Capmatinib (INCB28060)',
    'Capreomycin Sulfate',
    'Captopril',
    'Carbamazepine',
    'Carbazochrome sodium sulfonate (AC-17)',
    'Carbenicillin disodium',
    'Carbidopa',
    'Carbimazole',
    'Carboplatin',
    'Carfilzomib (PR-171)',
    'Carmofur',
    'Carprofen',
    'Carteolol HCl',
    'Carvedilol',
    'Caspofungin Acetate',
    'Catharanthine',
    'Cathepsin Inhibitor 1',
    'CAY10505',
    'CAY10603',
    'CB-839',
    'CC-401',
    'CCG 50014',
    'CCG-1423',
    'CCT007093',
    'CCT128930',
    'CCT129202',
    'CCT137690',
    'Cediranib',
    'Cediranib (AZD2171)',
    'Cefaclor',
    'Cefdinir',
    'Cefditoren Pivoxil',
    'Cefoperazone',
    'Cefoselis Sulfate',
    'Cefprozil hydrate',
    'Ceftiofur HCl',
    'Ceftriaxone Sodium Trihydrate',
    'Celastrol',
    'Celecoxib',
    'CEP-18770 (Delanzomib)',
    'CEP-32496',
    'CEP-33779',
    'Cephalexin',
    'Cephalomannine',
    'Cepharanthine',
    'Cerdulatinib (PRT062070, PRT2070)',
    'Ceritinib',
    'Cetirizine DiHCl',
    'Cetrimonium Bromide (CTAB)',
    'Cetrorelix Acetate',
    'Cetylpyridinium Chloride',
    'CFTRinh-172',
    'CG-930',
    'CGC-11047',
    'CGC-11144',
    'CGI1746',
    'CGK 733',
    'CGK733',
    'CGP 57380',
    'CGP-029482',
    'CGP60474',
    'CGP74514A',
    'CGS 21680 HCl',
    'CH-223191',
    'CH5132799',
    'CH5138303',
    'CH5183284',
    'CH5424802',
    'Chelerythrine',
    'Chenodeoxycholic Acid',
    'CHIR-124',
    'CHIR-98014',
    'CHIR-99021',
    'Chk2 inhibitor II',
    'Chloramphenicol',
    'Chlorhexidine HCl',
    'Chlormezanone',
    'Chloroambucil',
    'Chlorocresol',
    'Chlorogenic Acid',
    'Chloroprocaine HCl',
    'Chloroquine',
    'Chloroquine Phosphate',
    'Chlorothiazide',
    'Chloroxine',
    'Chlorpheniramine Maleate',
    'Chlorpromazine HCl',
    'Chlorpropamide',
    'Chlorprothixene',
    'Chlorquinaldol',
    'Chlortetracycline HCl',
    'Chlorzoxazone',
    'Cholesterol',
    'Choline Chloride',
    'Chromocarb',
    'Chrysin',
    'Chrysophanic Acid',
    'CI994 (Tacedinaline)',
    'Ciclopirox',
    'Ciclopirox ethanolamine',
    'CID755673',
    'Cidofovir',
    'Cilazapril Monohydrate',
    'Cilengitide',
    'Cilnidipine',
    'Cilomilast',
    'Cilostazol',
    'Cimetidine',
    'Cinacalcet HCl',
    'Cinchonidine',
    'Cinchophen',
    'Cinepazide maleate',
    'Ciprofibrate',
    'Ciprofloxacin',
    'Ciproxifan',
    'Cisatracurium Besylate',
    'Cisplatin',
    'CK-636',
    'CL-387785 (EKI-785)',
    'Cladribine',
    'Clarithromycin',
    'Clemastine Fumarate',
    'Clevidipine Butyrate',
    'Clevudine',
    'Climbazole',
    'Clinafloxacin',
    'Clindamycin',
    'Clindamycin HCl',
    'Clindamycin palmitate HCl',
    'Clindamycin Phosphate',
    'Clinofibrate',
    'Clobetasol propionate',
    'Clodronate Disodium',
    'Clofarabine',
    'Clofazimine',
    'Clofibric Acid',
    'Clomifene citrate',
    'Clomipramine HCl',
    'Clonidine HCl',
    'Clopidogrel',
    'Clopidol',
    'Clorprenaline HCl',
    'Clorsulon',
    'Closantel',
    'Closantel Sodium',
    'Clotrimazole',
    'Cloxacillin Sodium',
    'Clozapine',
    'CNX-2006',
    'CNX-774',
    'Cobicistat (GS-9350)',
    'Cobimetinib (GDC-0973, RG7420)',
    'Coenzyme Q10 (CoQ10)',
    'Colistin Sulfate',
    'Combretastatin A4',
    'Conivaptan HCl',
    'CORM-3',
    'Cortisone acetate',
    'Costunolide',
    'Coumarin',
    'CP466722',
    'CP-466722',
    'CP-673451',
    'CP724714',
    'CP-724714',
    'CP-91149',
    'CPI-169',
    'CPI-203',
    'CPI-613',
    'CPT-11',
    'Creatinine',
    'Crenolanib (CP-868596)',
    'Crizotinib',
    'Crizotinib (PF-02341066)',
    'CRT0044876',
    'Cryptotanshinone',
    'Crystal Violet',
    'CTB',
    'CTEP (RO4956371)',
    'CUDC-101',
    'CUDC-907',
    'Curcumin',
    'Curcumol',
    'CW069',
    'CX-4945 (Silmitasertib)',
    'CX-5461',
    'CX-6258 HCl',
    'CYC116',
    'Cyclamic acid',
    'Cyclandelate',
    'Cyclizine 2HCl',
    'Cyclo (-RGDfK)',
    'Cyclo(RGDyK)',
    'Cyclobenzaprine HCl',
    'Cyclocytidine HCl',
    'Cycloheximide',
    'Cyclopamine',
    'Cyclophosphamide Monohydrate',
    'Cyclosporin A',
    'Cyclosporine',
    'Cyclovirobuxin D',
    'Cyproheptadine HCl',
    'Cyproterone Acetate',
    'Cyromazine',
    'Cysteamine HCl',
    'CYT997 (Lexibulin)',
    'Cytarabine',
    'Cytidine',
    'Cytisine',
    'CZC24832',
    'D 4476',
    'Dabigatran (BIBR 953)',
    'Dabigatran Etexilate',
    'Dabrafenib',
    'Dacarbazine',
    'Daclatasvir (BMS-790052)',
    'Dacomitinib',
    'Dacomitinib (PF299804, PF299)',
    'Dactinomycin',
    'Daidzein',
    'Daidzin',
    'Dalcetrapib (JTT-705, RO4607381)',
    'Daminozide',
    'Danofloxacin Mesylate',
    'Danoprevir (ITMN-191)',
    'Danusertib (PHA-739358)',
    'Dapagliflozin',
    'Daphnetin',
    'Dapivirine (TMC120)',
    'Dapoxetine HCl',
    'DAPT (GSI-IX)',
    'Daptomycin',
    'Darapladib (SB-480848)',
    'Darifenacin HBr',
    'Darunavir Ethanolate',
    'Dasatinib',
    'Dasatinib Monohydrate',
    'Daunorubicin HCl',
    'DBeQ',
    'DCC-2036',
    'DCC-2036 (Rebastinib)',
    'D-Cycloserine',
    'Decamethonium Bromide',
    'Decitabine',
    'Decoquinate',
    'Defactinib (VS-6063, PF-04554878)',
    'Deferasirox',
    'Deferiprone',
    'Deflazacort',
    'Degrasyn (WP1130)',
    'Dehydroepiandrosterone (DHEA)',
    'Deltarasin',
    'Demeclocycline HCl',
    'Deoxyarbutin',
    'Deoxycorticosterone acetate',
    'Dequalinium Chloride',
    'Desloratadine',
    'Desmopressin (STIMATE, DDAVP, Minirin)',
    'Desonide',
    'Desvenlafaxine',
    'Desvenlafaxine Succinate',
    'Detomidine HCl',
    'Dexamethasone (DHAP)',
    'Dexamethasone Acetate',
    'Dexamethasone Sodium Phosphate',
    'Dexlansoprazole',
    'Dexmedetomidine',
    'Dexmedetomidine HCl',
    'Dexrazoxane HCl (ICRF-187, ADR-529)',
    'Dextrose',
    'D-glutamine',
    'Diacerein',
    'Dibenzothiophene',
    'Dibucaine HCl',
    'Dichloroacetate',
    'Dichlorphenamide',
    'Diclazuril',
    'Diclofenac Diethylamine',
    'Diclofenac Potassium',
    'Diclofenac Sodium',
    'Dicloxacillin Sodium',
    'Dicoumarol',
    'Didanosine',
    'Dienogest',
    'Diethylstilbestrol',
    'Difluprednate',
    'Digoxin',
    'Dihydroartemisinin (DHA)',
    'Dihydromyricetin',
    'Diltiazem HCl',
    'Dimesna',
    'Dimethyl Fumarate',
    'Diminazene Aceturate',
    'Dinaciclib',
    'Dinitolmide',
    'Dioscin',
    'Diosgenin',
    'Diosmetin',
    'Diosmin',
    'Diphemanil Methylsulfate',
    'Diphenhydramine HCl',
    'Diphenidol HCl',
    'Dipyridamole',
    'Dirithromycin',
    'Disodium Cromoglycate',
    'Disulfiram',
    'Divalproex Sodium',
    'DL-Adrenaline',
    'DL-Carnitine HCl',
    'D-Mannitol',
    'DMH1',
    'DMOG',
    'DMXAA (Vadimezan)',
    'Docetaxel',
    'Docetaxel Trihydrate',
    'Docosanol',
    'Dofetilide',
    'Dolutegravir (GSK1349572)',
    'Domiphen Bromide',
    'Domperidone',
    'Donepezil HCl',
    'Dopamine HCl',
    'Doramapimod',
    'Doripenem Hydrate',
    'Dorsomorphin',
    'Dorsomorphin 2HCl',
    'Dorzolamide HCl',
    'Dovitinib',
    'Dovitinib (TKI-258) Dilactic Acid',
    'Dovitinib (TKI258) Lactate',
    'Dovitinib (TKI-258, CHIR-258)',
    'Doxapram HCl',
    'Doxazosin Mesylate',
    'Doxercalciferol',
    'Doxifluridine',
    'Doxofylline',
    'Doxorubicin',
    'Doxycycline HCl',
    'Doxycycline Hyclate',
    'Doxylamine Succinate',
    'D-Pantothenic acid',
    'D-Phenylalanine',
    'Dronedarone HCl',
    'Droperidol',
    'Dropropizine',
    'Drospirenone',
    'Droxidopa',
    'Droxinostat',
    'DTP3',
    'Duloxetine HCl',
    'Dutasteride',
    'Duvelisib (IPI-145, INK1197)',
    'Dyclonine HCl',
    'Dydrogesterone',
    'Dynasore',
    'Dyphylline',
    'E3330',
    'E-64',
    'Ebastine',
    'Econazole nitrate',
    'Edaravone',
    'Edoxaban',
    'Efaproxiral Sodium',
    'EHop-016',
    'EHT 1864',
    'EI1',
    'Elacridar (GF120918)',
    'Elaiophylin',
    'Elcatonin Acetate',
    'Eledoisin Acetate',
    'Elesclomol (STA-4783)',
    'Eletriptan HBr',
    'Ellagic acid',
    'Eltrombopag',
    'Eltrombopag Olamine',
    'Elvitegravir (GS-9137, JTK-303)',
    'Embelin',
    'Emodin',
    'Empagliflozin (BI 10773)',
    'Emtricitabine',
    'Enalapril Maleate',
    'Enalaprilat Dihydrate',
    'Encorafenib (LGX818)',
    'Endothelin-1 Acetate',
    'Endoxifen HCl',
    'Enfuvirtide Acetate (T-20)',
    'ENMD-2076',
    'ENMD-2076 L-(+)-Tartaric acid',
    'Enoxacin',
    'Enoxolone',
    'Enrofloxacin',
    'Entacapone',
    'Entecavir Hydrate',
    'Entinostat',
    'Entospletinib',
    'Entospletinib (GS-9973)',
    'Enzalutamide',
    'Enzastaurin',
    'EO1428',
    'Epalrestat',
    'Epiandrosterone',
    'Epigallocatechin gallate',
    'Epinastine HCl',
    'Epinephrine Bitartrate',
    'Epinephrine HCl',
    'Epirubicin',
    'Epirubicin HCl',
    'Eplerenone',
    'Epothilone A',
    'Epothilone B (EPO906, Patupilone)',
    'Eprazinone 2HCl',
    'Eprosartan Mesylate',
    'Eptifibatide Acetate',
    'EPZ004777',
    'EPZ005687',
    'EPZ015666',
    'EPZ5676',
    'EPZ-6438',
    'Equol',
    'Erastin',
    'Erdosteine',
    'Ergosterol',
    'ERK5-IN-1',
    'Erlotinib',
    'Erlotinib HCl (OSI-744)',
    'Erteberel (LY500307)',
    'Erythritol',
    'Erythromycin',
    'Erythromycin Cyclocarbonate',
    'Erythromycin Ethylsuccinate',
    'Escitalopram Oxalate',
    'Esculin',
    'ESI-09',
    'Esmolol HCl',
    'Esomeprazole Magnesium',
    'Esomeprazole Sodium',
    'Estradiol',
    'Estradiol Benzoate',
    'Estradiol Cypionate',
    'Estradiol valerate',
    'Estriol',
    'Estrone',
    'Ethacridine lactate monohydrate',
    'Ethambutol HCl',
    'Ethamsylate',
    'Ethinyl Estradiol',
    'Ethionamide',
    'Ethisterone',
    'Ethynodiol diacetate',
    'Etidronate',
    'Etizolam',
    'Etodolac',
    'Etofibrate',
    'Etomidate',
    'Etoposide',
    'ETP-46464',
    'Etravirine (TMC125)',
    'EUK 134',
    'Evacetrapib (LY2484595)',
    'Everolimus',
    'Evodiamine',
    'EW-7197',
    'Exemestane',
    'Exenatide Acetate',
    'Ezetimibe',
    'Famciclovir',
    'Famotidine',
    'Fascaplysin',
    'Fasudil (HA-1077) HCl',
    'Febuxostat',
    'Fedratinib (SAR302503, TG101348)',
    'Felbamate',
    'Felodipine',
    'Felypressin Acetate',
    'Fenbendazole',
    'Fenofibrate',
    'Fenoprofen Calcium',
    'Fenoprofen calcium hydrate',
    'Fenspiride HCl',
    'Fenticonazole Nitrate',
    'Ferrostatin-1 (Fer-1)',
    'Ferulic Acid',
    'Fesoterodine Fumarate',
    'Fexofenadine HCl',
    'FH1(BRD-K4477)',
    'FH535',
    'Fidaxomicin',
    'Filgotinib',
    'Finasteride',
    'Fingolimod (FTY720) HCl',
    'Fisetin',
    'FK866 (APO866, Daporinad)',
    'Flavoxate HCl',
    'Fleroxacin',
    'FLI-06',
    'Flopropione',
    'Florfenicol',
    'Floxuridine',
    'Flubendazole',
    'Fluconazole',
    'Flucytosine',
    'Fludarabine',
    'Fludarabine Phosphate',
    'Flufenamic acid',
    'Flumazenil',
    'Flumequine',
    'Flumethasone',
    'Flunarizine 2HCl',
    'Flunixin Meglumin',
    'Fluocinolone Acetonide',
    'Fluocinonide',
    'Fluorometholone Acetate',
    'Fluorouracil (5-Fluoracil, 5-FU)',
    'Fluoxetine HCl',
    'Flupirtine maleate',
    'Flurbiprofen',
    'Flutamide',
    'Fluticasone propionate',
    'Fluvastatin',
    'Fluvastatin Sodium',
    'Fluvoxamine maleate',
    'Foretinib',
    'Foretinib (GSK1363089)',
    'Formestane',
    'Formononetin',
    'Formoterol Hemifumarate',
    'Forskolin',
    'Fosaprepitant dimeglumine salt',
    'Fosbretabulin (Combretastatin A4 Phosphate (CA4P)) Disodium',
    'Foscarnet Sodium',
    'Fosinopril Sodium',
    'Fostamatinib (R788)',
    'FPH1 (BRD-6125)',
    'FPH2 (BRD-9424)',
    'FR180204',
    'FRAX597',
    'FTase Inhibitor I',
    'FTI 277 HCl',
    'Fudosteine',
    'Fulvestrant',
    'Furaltadone HCl',
    'Furosemide',
    'G-749',
    'Gabapentin',
    'Gabapentin HCl',
    'Gabexate Mesylate',
    'Gadodiamide',
    'Galanthamine HBr',
    'Galeterone',
    'Gallamine Triethiodide',
    'Galunisertib (LY2157299)',
    'Gambogic Acid',
    'Ganciclovir',
    'Gandotinib (LY2784544)',
    'Ganetespib',
    'GANT61',
    'Garcinol',
    'Gastrodin',
    'Gatifloxacin',
    'GDC-0068',
    'GDC-0152',
    'GDC-0349',
    'GDC-0879',
    'GDC-0941',
    'GDC-0980',
    'GDC-0994',
    'Gedatolisib (PF-05212384, PKI-587)',
    'Gefitinib',
    'Geldanamycin',
    'Gemcitabine',
    'Gemcitabine HCl',
    'Gemfibrozil',
    'Geneticin (G418 Sulfate)',
    'Genipin',
    'Geniposide',
    'Geniposidic acid',
    'Genistein',
    'Gentamicin Sulfate',
    'Gestodene',
    'GF109203X',
    'Gimeracil',
    'Ginkgolide A',
    'Ginkgolide B',
    'Givinostat (ITF2357)',
    'GKT137831',
    'Glasdegib (PF-04449913)',
    'Gliclazide',
    'Glimepiride',
    'Glipizide',
    'Gliquidone',
    'GLP-1 (7-37) Acetate',
    'GLPG0634 analogue',
    'Glucagon HCl',
    'Glyburide (Glibenclamide)',
    'Glycyl-H-1152',
    'Glycyrrhizin (Glycyrrhizic Acid)',
    'GM6001',
    'GNE-0877',
    'GNE-317',
    'GNE7915',
    'GNE-7915',
    'GNE-9605',
    'GNF2',
    'GNF-2',
    'GNF-5',
    'GNF-5837',
    'Go 6976',
    'Go 6983',
    'Go6976',
    'Go-6983',
    'Golgicide A',
    'Golvatinib (E7050)',
    'Gonadorelin Acetate',
    'Gossypol',
    'Gramine',
    'Granisetron HCl',
    'Grape Seed Extract',
    'Griseofulvin',
    'GSK 690693',
    'GSK J1',
    'GSK J4 HCl',
    'GSK1059615',
    'GSK1070916',
    'GSK126',
    'GSK1292263',
    'GSK1324726A (I-BET726)',
    'GSK1838705A',
    'GSK1904529A',
    'GSK2334470',
    'GSK256066',
    'GSK2578215A',
    'GSK2606414',
    'GSK2636771',
    'GSK2656157',
    'GSK2830371',
    'GSK343',
    'GSK3787',
    'GSK429286A',
    'GSK461364',
    'GSK650394',
    'GSK690693',
    'GSK923295',
    'GSK-J1',
    'GSK-J2',
    'GSK-J4',
    'GSK-LSD1 2HCl',
    'GTPL5944',
    'GTPL6019',
    'GTPL6027',
    'Guaifenesin',
    'Guanabenz Acetate',
    'Guanidine HCl',
    'Guanosine',
    'Guanosine Hydrate',
    'GW 1516',
    'GW0742',
    'GW2580',
    'GW3965 HCl',
    'GW4064',
    'GW441756',
    'GW5074',
    'GW-5074',
    'GW788388',
    'GW791343 HCl',
    'GW842166X',
    'GW843682X',
    'GW9508',
    'GW9662',
    'Gynostemma Extract',
    'GZD824 Dimesylate',
    'H 89 2HCl',
    'H-8',
    'H89',
    'HA14-1',
    'Halcinonide',
    'Halobetasol Propionate',
    'Haloperidol',
    'HC-030031',
    'Hematoxylin',
    'Heparin sodium',
    'Heparin sodium 180 U/mg',
    'Hesperadin',
    'Hesperetin',
    'Hesperidin',
    'Hexamethonium Bromide',
    'Hexestrol',
    'HG-14-10-04',
    'HG-14-8-02',
    'HG-5-113-01',
    'HG-5-88-01',
    'HG-6-64-01',
    'HG-9-91-01',
    'Histamine 2HCl',
    'Histamine Phosphate',
    'HJC0350',
    'HMN-214',
    'HO-3867',
    'Homatropine Bromide',
    'Homatropine Methylbromide',
    'Honokiol',
    'Hordenine',
    'HPOB',
    'HS-173',
    'HSP990 (NVP-HSP990)',
    'HTH-01-015',
    'Hydralazine HCl',
    'Hydrochlorothiazide',
    'Hydrocortisone',
    'Hydroxychloroquine Sulfate',
    'Hydroxypropyl Cellulose',
    'Hydroxyurea',
    'Hydroxyzine 2HCl',
    'Hygromycin B',
    'Hyodeoxycholic acid (HDCA)',
    'Hyoscyamine',
    'Hypoxanthine',
    'Ibandronate',
    'Ibandronate sodium',
    'I-BET',
    'I-BET151',
    'I-BET-762',
    'Ibrutinib',
    'Ibuprofen',
    'Ibuprofen Lysine',
    'Ibutilide Fumarate',
    'IC-87114',
    'Icariin',
    'ICG-001',
    'Icotinib',
    'ICRF-193',
    'ID-8',
    'Idarubicin HCl',
    'Idasanutlin (RG-7388)',
    'Idebenone',
    'Idoxuridine',
    'IEM 1754 2HBr',
    'Ifenprodil Tartrate',
    'Ifosfamide',
    'IKK16',
    'IKK-16 (IKK Inhibitor VII)',
    'Ilomastat (GM6001, Galardin)',
    'Iloperidone',
    'IM-12',
    'Imatinib',
    'Imatinib (STI571)',
    'Imatinib Mesylate (STI571)',
    'IMD 0354',
    'Imidapril HCl',
    'Imiquimod',
    'INCB024360',
    'Indacaterol Maleate',
    'Indapamide',
    'Indirubin',
    'Indole-3-carbinol',
    'Indomethacin',
    'Indoximod (NLG-8189)',
    'INH1',
    'INH6',
    'Iniparib',
    'Iniparib (BSI-201)',
    'INK-128',
    'INO-1001 (3-Aminobenzamide)',
    'Inosine',
    'Inulin',
    'IOWH032',
    'IOX1',
    'IOX2',
    'IP6K/IP3K inhibitor',
    'IPA-3',
    'Ipratropium Bromide',
    'Ipriflavone (Osteofix)',
    'Irbesartan',
    'Irinotecan HCl Trihydrate',
    'Irsogladine',
    'Ischemin',
    'Isepamicin Sulphate',
    'Isoconazole nitrate',
    'Isoliquiritigenin',
    'Isoniazid',
    'Isoprenaline HCl',
    'Isosorbide',
    'Isotretinoin',
    'Isovaleramide',
    'Ispinesib',
    'Isradipine',
    'ISRIB (trans-isomer)',
    'Istradefylline',
    'Itraconazole',
    'IU1',
    'Ivabradine HCl',
    'Ivacaftor (VX-770)',
    'Ivermectin',
    'IWP-2',
    'IWP-L6',
    'IWR-1-endo',
    'Ixabepilone',
    'Ixazomib (MLN2238)',
    'JIB-04',
    'JNJ 26854165',
    'JNJ-10198409',
    'JNJ-1661010',
    'JNJ-26854165 (Serdemetan)',
    'JNJ38877605',
    'JNJ-38877605',
    'JNJ-7706621',
    'JNJ-7777120',
    'JNK-9L',
    'JNK-IN-11',
    'JNK-IN-5A',
    'JNK-IN-8',
    'JSH-23',
    'JTC-801',
    'JW55',
    'JW-7-24-1',
    'JWE-035',
    'JZL 184',
    'K02288',
    'Kaempferol',
    'Kartogenin',
    'Ketanserin',
    'Ketoconazole',
    'Ketoprofen',
    'Ketorolac',
    'Ketotifen Fumarate',
    'Ki16198',
    'Ki16425',
    'Ki20227',
    'Ki8751',
    'KIN001-021',
    'KIN001-042',
    'KIN001-043',
    'KIN001-055',
    'KIN001-111',
    'KIN001-123',
    'KIN001-127',
    'KIN001-135',
    'KIN001-220',
    'KIN001-242',
    'KIN001-244',
    'KIN001-260',
    'KIN001-266',
    'KIN001-269',
    'KIN001-270',
    'Kin236',
    'Kin237',
    'Kinetin',
    'KN62',
    'KN-62',
    'KN-93',
    'KN-93 Phosphate',
    'KNK437',
    'KPT-185',
    'KPT-276',
    'K-Ras(G12C) inhibitor 12',
    'K-Ras(G12C) inhibitor 6',
    'K-Ras(G12C) inhibitor 9',
    'KRN 633',
    'KRN633',
    'KU-0060648',
    'KU-0063794',
    'KU55933',
    'KU-55933 (ATM Kinase Inhibitor)',
    'KU-60019',
    'KU63794',
    'KW2449',
    'KW-2478',
    'KX01',
    'KY02111',
    'L-(+)-Rhamnose Monohydrate',
    'L-779450',
    'Labetalol HCl',
    'Lacidipine',
    'Lactulose',
    'L-Adrenaline',
    'Laetrile',
    'Lafutidine',
    'Lamivudine',
    'Lamotrigine',
    'Lansoprazole',
    'Lapatinib',
    'Lappaconite HBr',
    'LAQ824 (Dacinostat)',
    'Laquinimod',
    'L-Arginine HCl (L-Arg)',
    'L-Ascorbyl 6-palmitate',
    'Latrepirdine',
    'LB-100',
    'LB42708',
    'LBH589',
    'L-carnitine',
    'LCL161',
    'LCZ696',
    'LDC000067',
    'LDC1267',
    'LDE225 (NVP-LDE225,Erismodegib)',
    'LDN-193189',
    'LDN-193189 HCl',
    'LDN-212854',
    'LDN-214117',
    'LDN-57444',
    'Lecirelin (Dalmarelin) Acetate',
    'Ledipasvir (GS5885)',
    'Leflunomide',
    'Lenalidomide',
    'Lenalidomide (CC-5013)',
    'Lenvatinib (E7080)',
    'Lestaurtinib',
    'Letrozole',
    'Leucovorin Calcium',
    'Leupeptin Hemisulfate',
    'Leuprorelin Acetate',
    'Levetiracetam',
    'Levobetaxolol HCl',
    'Levobupivacaine HCl',
    'Levodopa',
    'Levodropropizine',
    'Levofloxacin',
    'Levonorgestrel',
    'Levosimendan',
    'Levosulpiride',
    'LFM-A13',
    'LFM-A13/DDE-28',
    'LGK-974',
    'L-Glutamine',
    'Licochalcone A',
    'Licofelone',
    'Lidocaine',
    'Limonin',
    'Linagliptin',
    'Lincomycin HCl',
    'Linezolid',
    'Linifanib',
    'Linsitinib',
    'Liothyronine Sodium',
    'Liproxstatin-1',
    'Liranaftate',
    'Lisinopril',
    'Lithocholic acid',
    'L-Mimosine',
    'LMK-235',
    'L-NAME HCl',
    'Lomefloxacin HCl',
    'Lomeguatrib',
    'Lomerizine HCl',
    'Lomitapide',
    'Lomitapide Mesylate',
    'Lomustine',
    'Lonafarnib',
    'Lonidamine',
    'Loperamide HCl',
    'Lopinavir',
    'Loratadine',
    'Lorcaserin HCl',
    'Lornoxicam',
    'Losartan Potassium (DuP 753)',
    'Losmapimod',
    'Losmapimod (GW856553X)',
    'Loteprednol etabonate',
    'Lovastatin',
    'Loxapine Succinate',
    'Loxistatin Acid (E-64C)',
    'L-Thyroxine',
    'Lubiprostone',
    'Luliconazole',
    'Luminespib',
    'Luminespib (AUY-922, NVP-AUY922)',
    'Lumiracoxib',
    'Lurasidone HCl',
    'Luteolin',
    'LY2090314',
    'LY2109761',
    'LY2119620',
    'LY2409881',
    'LY2584702',
    'LY-2584702',
    'LY2584702 Tosylate',
    'LY2603618',
    'LY2608204',
    'LY2811376',
    'LY2874455',
    'LY2886721',
    'LY294002',
    'LY3009120',
    'LY310762',
    'LY364947',
    'LY404039',
    'LY411575',
    'Lypressin Acetate',
    'Lysipressin Acetate',
    'M344',
    'Macitentan',
    'Magnolol',
    'Malotilate',
    'Manidipine',
    'Manidipine 2HCl',
    'Maprotiline HCl',
    'Maraviroc',
    'Marbofloxacin',
    'Marimastat(BB-2516)',
    'Masitinib',
    'MC1568',
    'Mdivi-1',
    'ME0328',
    'Mebendazole',
    'Mecarbinate',
    'Mechlorethamine HCl',
    'Meclizine 2HCl',
    'Meclofenamate Sodium',
    'Meclofenoxate (Centrophenoxine) HCl',
    'Medetomidine HCl',
    'Medroxyprogesterone acetate',
    'Mefenamic Acid',
    'Mefloquine HCl',
    'Megestrol Acetate',
    'Meglumine',
    'Melanotan I',
    'Melanotan II',
    'Melatonin',
    'Meloxicam',
    'Memantine HCl',
    'Menadione',
    'Mepivacaine HCl',
    'Meprednisone',
    'Meptazinol HCl',
    'Mequinol',
    'Mercaptopurine (6-MP)',
    'Meropenem',
    'Mesalamine',
    'Mesna',
    'Mestranol',
    'Metformin HCl',
    'Methacycline HCl',
    'Methazolamide',
    'Methenamine',
    'Methimazole',
    'Methocarbamol',
    'Methotrexate',
    'Methoxsalen',
    'Methscopolamine',
    'Methyclothiazide',
    'Methyldopa',
    'Methylglyoxal',
    'Methyl-Hesperidin',
    'Methylprednisolone',
    'Methylstat',
    'Methylthiouracil',
    'Metoclopramide HCl',
    'Metolazone',
    'Metoprolol Tartrate',
    'Metronidazole',
    'Mevastatin',
    'Mexiletine HCl',
    'Mezlocillin Sodium',
    'MG-101 (ALLN)',
    'MG-132',
    'MG149',
    'MGCD265',
    'MGCD-265',
    'MHY1485',
    'MI-2 (MALT1 inhibitor)',
    'MI-2 (Menin-MLL Inhibitor)',
    'MI-3 (Menin-MLL Inhibitor)',
    'MI-773 (SAR405838)',
    'Mianserin HCl',
    'Micafungin Sodium',
    'Miconazole',
    'Miconazole Nitrate',
    'Mifepristone',
    'Miglitol',
    'Milciclib (PHA-848125)',
    'Mildronate',
    'Milnacipran HCl',
    'Milrinone',
    'Miltefosine',
    'Minocycline HCl',
    'Minoxidil',
    'Mirabegron',
    'Mirtazapine',
    'Mitiglinide Calcium',
    'Mitomycin C',
    'Mitotane',
    'Mitoxantrone',
    'Mitoxantrone HCl',
    'Mizolastine',
    'Mizoribine',
    'MK 1775',
    'MK-0752',
    'MK-1775',
    'MK-2048',
    'MK2206',
    'MK-2206 2HCl',
    'MK-2461',
    'MK-2866 (GTx-024)',
    'MK-3207 HCl',
    'MK-5108 (VX-689)',
    'MK-801 (Dizocilpine)',
    'MK-8245',
    'MK-8745',
    'MK-8776 (SCH 900776)',
    'ML130 (Nodinitib-1)',
    'ML133 HCl',
    'ML141',
    'ML161',
    'ML167',
    'ML323',
    'ML324',
    'ML347',
    'ML-7',
    'ML-9',
    'MLN0905',
    'MLN4924',
    'MLN8054',
    'MLN9708',
    'MM-102',
    'MNS (3,4-Methylenedioxy-β-nitrostyrene, MDBN)',
    'Mocetinostat',
    'Moclobemide (Ro 111163)',
    'Moexipril HCl',
    'Moguisteine',
    'Momelotinib',
    'Mometasone furoate',
    'Monensin',
    'Monobenzone',
    'Montelukast Sodium',
    'Morin Hydrate',
    'Moroxydine HCl',
    'Mosapride Citrate',
    'Motesanib',
    'Motesanib Diphosphate (AMG-706)',
    'Moxifloxacin HCl',
    'Moxonidine',
    'Mozavaptan',
    'MPEP',
    'MPI-0479605',
    'MPS-1-IN-1',
    'MRS 2578',
    'MRT67307',
    'MS436',
    'MSDC-0160',
    'Mubritinib (TAK 165)',
    'Mupirocin',
    'Mycophenolate Mofetil',
    'Mycophenolic acid',
    'Myelin Oligodendrocyte Glycoprotien (35-55) rat MOG (35-55)',
    'Myricetin',
    'Myricitrin',
    'N6022',
    'N6-methyladenosine (m6A)',
    'Nabumetone',
    'NAD+',
    'Nadifloxacin',
    'Nafamostat Mesylate',
    'Nafarelin Acetate',
    'Nafcillin Sodium',
    'Naftifine HCl',
    'Naftopidil',
    'Naftopidil DiHCl',
    'Nalidixic acid',
    'Naloxone HCl',
    'Naloxone HCl Dihydrate',
    'Naltrexone HCl',
    'Nanchangmycin',
    'Naphazoline HCl',
    'Naproxen Sodium',
    'Naratriptan',
    'Naringenin',
    'Naringin',
    'Naringin Dihydrochalcone',
    'Natamycin',
    'Nateglinide',
    'Nebivolol',
    'Necrostatin-1',
    'Nedaplatin',
    'Nefiracetam',
    'Nefopam HCl',
    'Nelarabine',
    'Nelfinavir',
    'Nelfinavir Mesylate',
    'Neohesperidin',
    'Neohesperidin Dihydrochalcone (Nhdc)',
    'Neomycin sulfate',
    'Neostigmine Bromide',
    'Nepafenac',
    'Nepicastat (SYN-117) HCl',
    'Neratinib',
    'Netilmicin Sulfate',
    'Nevirapine',
    'Nexturastat A',
    'NG25',
    'NH125',
    'Nicaraven',
    'Nicardipine HCl',
    'Niclosamide',
    'Nicorandil',
    'Nicotinamide (Vitamin B3)',
    'Nicotinic Acid',
    'Nifedipine',
    'Niflumic acid',
    'Nifuroxazide',
    'Nilotinib',
    'Nilvadipine',
    'Nimesulide',
    'Nimodipine',
    'Nintedanib',
    'Nintedanib (BIBF 1120)',
    'Nisoldipine',
    'Nitazoxanide',
    'Nitenpyram',
    'Nithiamide',
    'Nitrendipine',
    'Nitrofural',
    'Nizatidine',
    'NLG919',
    'NMDA (N-Methyl-D-aspartic acid)',
    'NMS-1286937',
    'NMS-873',
    'NMS-E973',
    'NMS-P937 (NMS1286937)',
    'Nobiletin',
    'Nocodazole',
    'Noradrenaline bitartrate monohydrate',
    'Norethindrone',
    'Norfloxacin',
    'Novobiocin Sodium',
    'NPK76-II-72-1',
    'NPS-1034',
    'NPS-2143',
    'NSC 207895',
    'NSC 23766',
    'NSC 319726',
    'NSC 405020',
    'NSC 663284',
    'NSC697923',
    'NSC-87877',
    'NU1025',
    'NU6027',
    'NU6102',
    'NU7026',
    'NU7441',
    'NU7441 (KU-57788)',
    'Nutlin 3a',
    'Nutlin-3',
    'Nutlin-3a',
    'Nutlin-3b',
    'NVP-ADW742',
    'NVP-AEW541',
    'NVP-BEP800',
    'NVP-BGT226',
    'NVP-BHG712',
    'NVP-BSK805 2HCl',
    'NVP-BVU972',
    'NVP-TAE226',
    'NVP-TAE684',
    'NXY-059',
    'Nystatin (Fungicidin)',
    'OAC1',
    'Obatoclax Mesylate (GX15-070)',
    'Obeticholic Acid',
    'OC000459',
    'Octreotide Acetate',
    'Odanacatib (MK-0822)',
    'OF-1',
    'Ofloxacin',
    'OG-L002',
    'Olanzapine',
    'Olaparib',
    'Oleanolic Acid',
    'Oligomycin A',
    'Olmesartan Medoxomil',
    'Olomoucine II',
    'Olopatadine HCl',
    'Olsalazine Sodium',
    'Omecamtiv mecarbil (CK-1827452)',
    'Omeprazole',
    'Omipalisib',
    'Onalespib (AT13387)',
    'Ondansetron',
    'Ondansetron HCl',
    'ONX-0914 (PR-957)',
    'Oprozomib (ONX 0912)',
    'Optovin',
    'Orbifloxacin',
    'Org 27569',
    'Oridonin',
    'Orlistat',
    'Ornidazole',
    'Ornipressin Acetate',
    'Orotic acid (6-Carboxyuracil)',
    'Orphenadrine Citrate',
    'Oseltamivir Phosphate',
    'OSI-027',
    'OSI-420',
    'OSI-930',
    'Ospemifene',
    'Osthole',
    'OSU-03012 (AR-12)',
    'Otenabant (CP-945598) HCl',
    'Otilonium Bromide',
    'OTSSP167',
    'OTX015',
    'Ouabain',
    'Oxacillin sodium monohydrate',
    'Oxaliplatin',
    'Oxamflatin',
    'Oxaprozin',
    'Oxcarbazepine',
    'Oxfendazole',
    'Oxibendazole',
    'Oxiracetam',
    'Oxybuprocaine HCl',
    'Oxybutynin',
    'Oxybutynin chloride',
    'Oxymatrine',
    'Oxymetazoline HCl',
    'Oxytetracycline (Terramycin)',
    'Oxytetracycline Dihydrate',
    'Oxytocin (Syntocinon)',
    'Ozagrel',
    'Ozagrel HCl',
    'P22077',
    'P5091 (P005091)',
    'P529',
    'PA-824',
    'PAC-1',
    'Pacritinib',
    'Paeoniflorin',
    'Paeonol',
    'Palbociclib',
    'Palbociclib (PD-0332991) HCl',
    'Paliperidone',
    'Palmatine chloride',
    'Palmitoyl Pentapeptide',
    'Palonosetron HCl',
    'Pamidronate Disodium',
    'Pancuronium dibromide',
    'Paromomycin Sulfate',
    'Paroxetine HCl',
    'Pazopanib',
    'Pazopanib HCl (GW786034 HCl)',
    'PCI-24781 (Abexinostat)',
    'PCI-34051',
    'PD 151746',
    'PD 98059',
    'PD0325901',
    'PD123319',
    'PD128907 HCl',
    'PD153035 HCl',
    'PD168393',
    'PD173074',
    'PD173955',
    'PD184352',
    'PD318088',
    'PD98059',
    'Pefloxacin Mesylate',
    'Pefloxacin Mesylate Dihydrate',
    'Pelitinib',
    'Pemetrexed',
    'Pemetrexed Disodium Hydrate',
    'Pemirolast potassium',
    'Penciclovir',
    'Penfluridol',
    'Penicillamine',
    'Penicillin G Sodium',
    'Pentamidine',
    'Pentoxyverine Citrate',
    'Pepstatin A',
    'Peramivir Trihydrate',
    'Pergolide Mesylate',
    'Perifosine (KRX-0401)',
    'Perindopril Erbumine',
    'Pexidartinib (PLX3397)',
    'Pexmetinib (ARRY-614)',
    'PF 3644022',
    'PF 573228',
    'PF-00562271',
    'PF-03814735',
    'PF04217903',
    'PF-04217903',
    'PF-04620110',
    'PF-04691502',
    'PF-04929113 (SNX-5422)',
    'PF-06463922',
    'PF-2545920',
    'PF-3716556',
    'PF-3758309',
    'PF-3845',
    'PF431396',
    'PF-431396',
    'PF-4708671',
    'PF477736',
    'PF-477736',
    'PF-4981517',
    'PF-5274857',
    'PF-543',
    'PF562271',
    'PF-562271',
    'PF-562271 HCl',
    'PF-573228',
    'PFI-1',
    'PFI-1 (PF-6405761)',
    'PFI-2',
    'PFI-3',
    'PFK15',
    'PH-797804',
    'PHA-665752',
    'PHA-680632',
    'PHA-767491',
    'PHA-793887',
    'Phenacetin',
    'Phenazopyridine HCl',
    'Phenformin HCl',
    'Phenindione',
    'Pheniramine Maleate',
    'Phenothiazine',
    'Phenoxybenzamine HCl',
    'Phentolamine Mesylate',
    'Phenylbutazone',
    'Phenylephrine HCl',
    'Phenytoin',
    'Phenytoin Sodium',
    'Phloretin',
    'Phlorizin',
    'Phosphoramidon Disodium Salt',
    'PHT-427',
    'PI103',
    'PI-103',
    'PI-1840',
    'PI-3065',
    'PI3K-IN-1',
    'Piceatannol',
    'Picropodophyllin (PPP)',
    'Pidotimod',
    'Pifithrin-α (PFTα)',
    'Pifithrin-μ',
    'PIK-293',
    'PIK-294',
    'PIK-75',
    'PIK-90',
    'PIK-93',
    'Pilocarpine HCl',
    'PIM12 kinase inhibitor V',
    'Pimasertib (AS-703026)',
    'Pimecrolimus',
    'Pimobendan',
    'Pioglitazone',
    'Pioglitazone HCl',
    'Piperacillin Sodium',
    'Piperine',
    'Piperlongumine',
    'Piracetam',
    'Pirarubicin',
    'Pirfenidone',
    'Piroxicam',
    'Pitavastatin Calcium',
    'Pizotifen Malate',
    'PJ34 HCl',
    'PKC412',
    'PKI-402',
    'Plerixafor (AMD3100)',
    'Plerixafor 8HCl (AMD3100 8HCl)',
    'Plinabulin (NPI-2358)',
    'PluriSIn #1 (NSC 14613)',
    'PLX-4720',
    'PMSF',
    'PND-1186 (VS-4718)',
    'PNU-120596',
    'Polydatin',
    'Pomalidomide',
    'Ponatinib',
    'Posaconazole',
    'Potassium Iodide',
    'Poziotinib',
    'PP1',
    'PP121',
    'PP2',
    'PP242',
    'PQ 401',
    'PR-619',
    'Pracinostat',
    'Pralatrexate',
    'Pramipexole',
    'Pramipexole 2HCl Monohydrate',
    'Pramiracetam',
    'Pramlintide Acetate',
    'Pramoxine HCl',
    'Pranlukast',
    'Pranoprofen',
    'Prasugrel',
    'Pravastatin sodium',
    'Praziquantel',
    'Prazosin HCl',
    'Prednisolone',
    'Prednisolone Acetate',
    'Prednisone',
    'Pregnenolone',
    'Prilocaine',
    'Primaquine Diphosphate',
    'Primidone',
    'Pritelivir (BAY 57-1293)',
    'Probenecid',
    'Probucol',
    'Procainamide HCl',
    'Procaine HCl',
    'Procarbazine HCl',
    'Proflavine Hemisulfate',
    'Progesterone',
    'Promethazine HCl',
    'Propafenone HCl',
    'Proparacaine HCl',
    'Propranolol HCl',
    'Propylthiouracil',
    'Protionamide',
    'PRT062607',
    'Prucalopride',
    'Prucalopride Succinate',
    'PRX-08066 Maleic acid',
    'PS-1145',
    'PTC-209',
    'PTC-209 HBr',
    'Puerarin',
    'PU-H71',
    'Purmorphamine',
    'Puromycin 2HCl',
    'Purvalanol A',
    'PX-478 2HCl',
    'PYR41',
    'PYR-41',
    'Pyrazinamide',
    'Pyridostatin Trifluoroacetate Salt',
    'Pyridostigmine Bromide',
    'Pyridoxine HCl',
    'Pyrimethamine',
    'QL-X-138',
    'QL-XI-92',
    'QL-XII-47',
    'QNZ',
    'Quercetin',
    'Quercetin Dihydrate',
    'Quetiapine Fumarate',
    'Quinacrine 2HCl',
    'Quinapril HCl',
    'Quinine HCl Dihydrate',
    'Quisinostat (JNJ-26481585)',
    'R 59-022',
    'R406',
    'R406 (free base)',
    'R428 (BGB324)',
    'R547',
    'R59949',
    'R788 (Fostamatinib) Disodium',
    'Racecadotril',
    'Radicicol',
    'RAF 265',
    'Raf265 derivative',
    'Ralimetinib',
    'Raloxifene HCl',
    'Raltegravir (MK-0518)',
    'Raltitrexed',
    'Ramelteon',
    'Ramipril',
    'Ranitidine',
    'Ranolazine',
    'Ranolazine 2HCl',
    'Rasagiline Mesylate',
    'RBC8',
    'Rebamipide',
    'Reboxetine mesylate',
    'Refametinib (RDEA119, Bay 86-9766)',
    'Regorafenib',
    'Remodelin',
    'Repaglinide',
    'RepSox',
    'Reserpine',
    'Resminostat',
    'Resveratrol',
    'Retapamulin',
    'Retinyl (Vitamin A) Palmitate',
    'Reversine',
    'RG108',
    'RG-108',
    'RG2833 (RGFP109)',
    'RGB-286147',
    'RGD (Arg-Gly-Asp) Peptides',
    'RGFP966',
    'Rheic Acid',
    'Rheochrysidin',
    'RI-1',
    'Ribavirin',
    'Ribitol',
    'Ribociclib',
    'Riboflavin',
    'Ribostamycin Sulfate',
    'Ridaforolimus (Deforolimus, MK-8669)',
    'Rifabutin',
    'Rifampin',
    'Rifapentine',
    'Rifaximin',
    'Rigosertib',
    'Rilmenidine Phosphate',
    'Rilpivirine',
    'Riluzole',
    'Rimantadine',
    'Rimonabant',
    'Risedronate',
    'Risedronate Sodium',
    'Risperidone',
    'RITA (NSC 652287)',
    'Ritodrine HCl',
    'Ritonavir',
    'Rivaroxaban',
    'Rivastigmine Tartrate',
    'Riviciclib',
    'Rizatriptan Benzoate',
    'RKI-1447',
    'RN486',
    'RO 31-8220',
    'Ro 31-8220 Mesylate',
    'Ro 32-0432',
    'Ro3280',
    'RO-3306',
    'RO4929097',
    'Rociletinib (CO-1686, AVL-301)',
    'Rocilinostat',
    'Rocuronium Bromide',
    'Rofecoxib',
    'Roflumilast',
    'Rolipram',
    'Romidepsin (FK228, Depsipeptide)',
    'Ronidazole',
    'Ropinirole HCl',
    'Ropivacaine HCl',
    'Rosiglitazone',
    'Rosiglitazone HCl',
    'Rosiglitazone maleate',
    'Rosuvastatin Calcium',
    'Rotigotine',
    'Rotundine',
    'Roxadustat (FG-4592)',
    'Roxatidine Acetate HCl',
    'Roxithromycin',
    'RS-127445',
    'Rucaparib',
    'Rucaparib (AG-014699,PF-01367338)',
    'Rufinamide',
    'Rupatadine Fumarate',
    'Rutaecarpine',
    'Rutin',
    'Ruxolitinib',
    'Ruxolitinib (INCB018424)',
    'RVX-208',
    'S- (+)-Rolipram',
    'S3I-201',
    'Sabutoclax',
    'Safinamide Mesylate',
    'SAL003',
    'Salbutamol Sulfate',
    'Salicin',
    'Salicylanilide',
    'Salidroside',
    'Salirasib',
    'Salmeterol Xinafoate',
    'Salmon Calcitonin Acetate',
    'Salubrinal',
    'SANT-1',
    'Santacruzamate A (CAY10683)',
    'Sapogenins Glycosides',
    'SAR131675',
    'Saracatinib',
    'Sarafloxacin HCl',
    'Sasapyrine',
    'Saxagliptin',
    'SB 203580',
    'SB 216763',
    'SB 239063',
    'SB202190',
    'SB202190 (FHPI)',
    'SB216763',
    'SB225002',
    'SB269970 HCl',
    'SB271046',
    'SB273005',
    'SB-334867',
    'SB-3CT',
    'SB408124',
    'SB415286',
    'SB431542',
    'SB505124',
    'SB525334',
    'SB590885',
    'SB705498',
    'SB742457',
    'SB743921',
    'SBE 13 HCl',
    'SC144',
    'SC-514',
    'SC75741',
    'SC79',
    'SCH 51344',
    'SCH772984',
    'Schisandrin B (Sch B)',
    'Sclareol',
    'Sclareolide',
    'Scopine',
    'Scopolamine HBr',
    'SCR7',
    'Scriptaid',
    'SD-208',
    'SecinH3',
    'Secnidazole',
    'Secretin Acetate',
    'Seliciclib',
    'Selinexor (KPT-330)',
    'Selisistat',
    'Selumetinib',
    'Semagacestat (LY450139)',
    'Semaxanib (SU5416)',
    'Sennoside A',
    'Sennoside B',
    'Serotonin HCl',
    'Sertaconazole nitrate',
    'Sertraline HCl',
    'Sesamin',
    'Sevelamer Carbonate',
    'Sevelamer HCl',
    'SF1670',
    'SGC 0946',
    'SGC-CBP30',
    'SGI-1027',
    'SGI-1776',
    'SGI-1776 free base',
    'SGX523',
    'SGX-523',
    'SH-4-54',
    'Shikimic Acid',
    'Shikonin',
    'Sigma A6730',
    'Sildenafil Citrate',
    'Silibinin',
    'Silodosin',
    'Silymarin',
    'Simvastatin',
    'Sincalide (Kinevac)',
    'Sinomenine',
    'Sirolimus',
    'Sirtinol',
    'Sitafloxacin Hydrate',
    'Sitagliptin phosphate monohydrate',
    'Sitaxentan sodium',
    'Skepinone-L',
    'SKI II',
    'SKLB1002',
    'SL-327',
    'SMI-4a',
    'SN-38',
    'SNAP-8',
    'SNS-032',
    'SNS-314 Mesylate',
    'SNX-2112 (PF-04928473)',
    'Sodium 4-Aminosalicylate',
    'Sodium ascorbate',
    'Sodium butyrate',
    'Sodium Danshensu',
    'Sodium Gluconate',
    'Sodium Monensin',
    'Sodium Monofluorophosphate',
    'Sodium Nitrite',
    'Sodium Nitroprusside',
    'Sodium orthovanadate',
    'Sodium Phenylbutyrate',
    'Sodium Picosulfate',
    'Sodium salicylate',
    'Sofosbuvir (PSI-7977, GS-7977)',
    'Solifenacin succinate',
    'Somatostatin Acetate',
    'Sophocarpine',
    'Sorafenib',
    'Sorafenib Tosylate',
    'Sorbitol',
    'Sotalol',
    'Sotrastaurin',
    'SP2509',
    'SP600125',
    'Sparfloxacin',
    'Spebrutinib',
    'Spectinomycin HCl',
    'Spiramycin',
    'Spironolactone',
    'Splenopentin Acetate',
    'Splitomicin',
    'SR-2516',
    'SRPIN340',
    'SRT1720',
    'SRT2104 (GSK2245840)',
    'S-Ruxolitinib',
    'S-Ruxolitinib (INCB018424)',
    'SSR128129E',
    'ST50842732',
    'Stattic',
    'Staurosporine',
    'Staurosporine aglycone',
    'Stavudine (d4T)',
    'StemRegenin 1 (SR1)',
    'STF-083010',
    'STF-118804',
    'STF-62247',
    'Stigmasterol',
    'Streptomycin sulfate',
    'Streptozotocin (STZ)',
    'S-Trityl-L-cysteine',
    'Strontium Ranelate',
    'SU11274',
    'SU6656',
    'SU9516',
    'Succinylcholine Chloride Dihydrate',
    'Sucralose',
    'Sulbactam',
    'Sulbactam sodium',
    'Sulconazole Nitrate',
    'Sulfacetamide Sodium',
    'Sulfadiazine',
    'Sulfadoxine',
    'Sulfaguanidine',
    'Sulfamerazine',
    'Sulfameter',
    'Sulfamethazine',
    'Sulfamethizole',
    'Sulfamethoxazole',
    'Sulfamethoxypyridazine',
    'Sulfanilamide',
    'Sulfapyridine',
    'Sulfasalazine',
    'Sulfathiazole',
    'Sulfisoxazole',
    'Sulindac',
    'Sulindac sulfide',
    'Sulphadimethoxine',
    'Sumatriptan Succinate',
    'Sunitinib',
    'Sunitinib Malate',
    'Suplatast Tosylate',
    'Suprofen',
    'Suvorexant (MK-4305)',
    'Synephrine',
    'Synephrine HCl',
    'T0070907',
    'T0901317',
    'Tacrolimus (FK506)',
    'Tadalafil',
    'TAI-1',
    'TAK-285',
    'TAK-632',
    'TAK-700 (Orteronel)',
    'TAK-715',
    'TAK-733',
    'TAK-875',
    'TAK-901',
    'Taladegib (LY2940680)',
    'Talazoparib (BMN 673)',
    'Talc',
    'Taltirelin Acetate',
    'TAME',
    'Tamibarotene',
    'Tamoxifen Citrate',
    'Tandutinib (MLN518)',
    'Tangeretin',
    'Tanshinone I',
    'Tanshinone IIA',
    'TAPI-0',
    'TAPI-1',
    'Tariquidar',
    'Taselisib',
    'Tasisulam',
    'Tasquinimod',
    'Taurine',
    'Taxifolin (Dihydroquercetin)',
    'Taxol',
    'Tazarotene',
    'TBCA',
    'TCID',
    'TCS 2312',
    'TCS 359',
    'TCS PIM-1 1',
    'TDZD-8',
    'Tebipenem Pivoxil',
    'Tegafur (FT-207, NSC 148958)',
    'Teicoplanin',
    'Telaprevir (VX-950)',
    'Telatinib',
    'Telbivudine',
    'Telmisartan',
    'Telotristat Etiprate (LX 1606 Hippurate)',
    'Temocapril HCl',
    'Temozolomide',
    'Tempol',
    'Temsirolimus',
    'Temsirolimus (CCI-779, NSC 683864)',
    'Tenatoprazole',
    'Teniposide',
    'Tenofovir',
    'Tenofovir Alafenamide (GS-7340)',
    'Tenofovir Disoproxil Fumarate',
    'Tenovin-1',
    'Tenovin-6',
    'Tenoxicam',
    'Tepotinib (EMD 1214063)',
    'Terazosin HCl',
    'Terbinafine',
    'Terbinafine HCl',
    'Terbutaline Sulfate',
    'Teriflunomide',
    'Teriparatide Acetate',
    'Terlipressin Acetate',
    'Tetracaine HCl',
    'Tetracycline HCl',
    'Tetrahydropapaverine HCl',
    'Tetrahydrozoline HCl',
    'Tetramisole HCl',
    'Tetrandrine',
    'TG 101348',
    'TG003',
    'TG100-115',
    'TG100713',
    'TG101209',
    'TGX221',
    'TGX-221',
    'TH588',
    'Thalidomide',
    'Thapsigargin',
    'Theobromine',
    'Thiabendazole',
    'Thiamet G',
    'Thiamine HCl (Vitamin B1)',
    'Thiamphenicol',
    'Thiazovivin',
    'Thioguanine',
    'Thymosin α1 Acetate',
    'Thymosin β4 Acetate (0.95)',
    'THZ1',
    'THZ-2-98-01',
    'Tianeptine sodium',
    'TIC10',
    'Ticagrelor',
    'Ticarcillin sodium',
    'Ticlopidine HCl',
    'Tideglusib',
    'Tigecycline',
    'Tilmicosin',
    'Timolol Maleate',
    'Tinidazole',
    'Tioconazole',
    'Tiopronin',
    'Tiotropium Bromide hydrate',
    'Tioxolone',
    'Tipifarnib',
    'Tiratricol',
    'Tirofiban',
    'Tivantinib',
    'Tivantinib (ARQ 197)',
    'Tivozanib',
    'Tizanidine HCl',
    'TMP269',
    'Tobramycin',
    'Tofacitinib',
    'Tofacitinib (CP-690550) Citrate',
    'Tofacitinib (CP-690550,Tasocitinib)',
    'Tolazoline HCl',
    'Tolbutamide',
    'Tolcapone',
    'Tolfenamic Acid',
    'Tolnaftate',
    'Tolperisone HCl',
    'Tolterodine tartrate',
    'Toltrazuril',
    'Tolvaptan',
    'Topiramate',
    'Topotecan',
    'Topotecan HCl',
    'Torcetrapib',
    'Toremifene Citrate',
    'Torin 1',
    'Torin 2',
    'Torin1',
    'Torin2',
    'Torsemide',
    'Tozasertib',
    'TPCA-1',
    'TRAM-34',
    'Trametinib',
    'Trametinib (GSK1120212)',
    'Tranexamic Acid',
    'Tranilast',
    'Tranylcypromine',
    'Trazodone HCl',
    'Trelagliptin',
    'Tretinoin',
    'Triamcinolone',
    'Triamcinolone Acetonide',
    'Triamterene',
    'Triapine',
    'Trichlormethiazide',
    'Trichostatin A',
    'Trichostatin A (TSA)',
    'Triciribine',
    'Triclabendazole',
    'Trifluoperazine 2HCl',
    'Trifluridine',
    'Triflusal',
    'Trilostane',
    'Trimebutine',
    'Trimethoprim',
    'Tripelennamine HCl',
    'Triptolide (PG490)',
    'Triptorelin Acetate',
    'Trometamol',
    'Tropicamide',
    'Tropisetron HCl',
    'Trospium chloride',
    'Troxerutin',
    'Troxipide',
    'TSU-68 (SU6668, Orantinib)',
    'TTNPB (Arotinoid Acid)',
    'Tubacin',
    'Tubastatin A',
    'Tubastatin A HCl',
    'Turofexorate Isopropyl (XL335)',
    'TW-37',
    'TWS119',
    'TX-1918',
    'Tylosin tartrate',
    'Tyrphostin 9',
    'Tyrphostin AG 1296',
    'Tyrphostin AG 879',
    'U-0126',
    'U0126-EtOH',
    'U-104',
    'U73122',
    'UK 383367',
    'Ulipristal',
    'Ulixertinib (BVD-523, VRT752271)',
    'UM729',
    'UMI-77',
    'UNC0379',
    'UNC0631',
    'UNC0638',
    'UNC1215',
    'UNC1999',
    'UNC2250',
    'UNC2881',
    'UNC669',
    'UPF 1069',
    'Uracil',
    'Urapidil HCl',
    'URB597',
    'Uridine',
    'URMC-099',
    'Ursodiol',
    'Ursolic Acid',
    'Valaciclovir HCl',
    'Valdecoxib',
    'Valganciclovir HCl',
    'Valnemulin HCl',
    'Valproic acid',
    'Valproic acid sodium salt (Sodium valproate)',
    'Valsartan',
    'Vancomycin HCl',
    'Vandetanib',
    'Vanillin',
    'Vanillylacetone',
    'Vapreotide Acetate',
    'Vardenafil HCl Trihydrate',
    'Varenicline Tartrate',
    'Varespladib (LY315920)',
    'Varlitinib',
    'Vasopressin Acetate',
    'Vatalanib (PTK787) 2HCl',
    'VE-821',
    'VE-822',
    'Vecuronium Bromide',
    'Veliparib',
    'Vemurafenib',
    'Venlafaxine',
    'VER155008',
    'VER-49009',
    'VER-50589',
    'Verapamil HCl',
    'Verdinexor (KPT-335)',
    'Verteporfin',
    'VGX-1027',
    'Vidarabine',
    'Vilazodone HCl',
    'Vildagliptin (LAF-237)',
    'Vinblastine',
    'Vincristine',
    'Vinflunine Tartrate',
    'Vinorelbine',
    'Vinorelbine Tartrate',
    'Vinpocetine',
    'Vismodegib (GDC-0449)',
    'Vitamin A Acetate',
    'Vitamin B12',
    'Vitamin C',
    'Vitamin D2',
    'Vitamin D3',
    'Voglibose',
    'Volasertib',
    'Volasertib (BI 6727)',
    'Vonoprazan Fumarate (TAK-438)',
    'Voreloxin (SNS-595)',
    'Voriconazole',
    'Vorinostat',
    'Vorinostat (SAHA, MK0683)',
    'Vortioxetine (Lu AA21004) HBr',
    'VS-5584 (SB2343)',
    'VU 0357121',
    'VU 0361737',
    'VU 0364439',
    'VU 0364770',
    'VUF 10166',
    'VX-11e',
    'VX-222 (VCH-222, Lomibuvir)',
    'VX-661',
    'VX-702',
    'VX-745',
    'VX-809 (Lumacaftor)',
    'WAY-100635 Maleate',
    'WAY-600',
    'WH-4-023',
    'WH-4-025',
    'WHI-P154',
    'WIKI4',
    'Withaferin A',
    'Wnt-C59 (C59)',
    'Wortmannin',
    'WP1066',
    'WS3',
    'WS6',
    'WY-14643 (Pirinixic Acid)',
    'WYE-125132',
    'WYE-125132 (WYE-132)',
    'WYE-354',
    'WYE-687',
    'WZ3105',
    'WZ3146',
    'WZ4002',
    'WZ4003',
    'WZ-4-145',
    'WZ-7043',
    'WZ8040',
    'WZ811',
    'Xanthohumol',
    'Xanthone',
    'XAV-939',
    'XEN445',
    'XL019',
    'XL147',
    'XL388',
    'XL413',
    'XL413 (BMS-863233)',
    'XL765',
    'XL888',
    'XMD11-50',
    'XMD11-85h',
    'XMD-12',
    'XMD13-2',
    'XMD14-99',
    'XMD15-27',
    'XMD16-144',
    'XMD8-85',
    'XMD8-92',
    'XRP44X',
    'Xylazine HCl',
    'Xylometazoline HCl',
    'Xylose',
    'Y-27632',
    'Y-27632 2HCl',
    'Y-320',
    'Y39983',
    'YH239-EE',
    'YK-4-279',
    'YM 201636',
    'YM155 (Sepantronium Bromide',
    'YM201636',
    'YO-01027 (Dibenzazepine)',
    'Yohimbine HCl',
    'YYA-021',
    'Zafirlukast',
    'Zalcitabine',
    'Zaltoprofen',
    'Zanamivir',
    'ZCL278',
    'Z-DEVD-FMK',
    'Zebularine',
    'Z-FA-FMK',
    'ZG-10',
    'Zibotentan (ZD4054)',
    'Zidovudine',
    'Zileuton',
    'Zinc Pyrithione',
    'Ziprasidone HCl',
    'Z-Leu-Leu-Norvalinal',
    'ZLN005',
    'ZM 306416',
    'ZM 323881 HCl',
    'ZM 336372',
    'ZM 39923 HCl',
    'ZM 447439',
    'ZM-447439',
    'Zoledronic Acid',
    'Zolmitriptan',
    'Zonisamide',
    'Zosuquidar (LY335979) 3HCl',
    'Zotarolimus(ABT-578)',
    'Zoxazolamine',
    'ZSTK474',
    'Z-VAD-FMK',
    'β-Sitosterol'

  ],
  diseases: [
    'Abdominal Aortic Aneurysm',
    'Acanthamoeba Infection',
    'ACE (Adverse Childhood Experiences)',
    'Acinetobacter Infection',
    'Acquired Immune Deficiency Syndrome (AIDS)',
    'Acquired Immunodeficiency Syndrome (AIDS)',
    'Adenovirus Infection',
    'Adenovirus Vaccination',
    'ADHD [Attention Deficit/Hyperactivity Disorder]',
    'Adult Vaccinations',
    'Adverse Childhood Experiences (ACE)',
    'African Trypanosomiasis',
    'Agricultural Safety',
    'AHF (Alkhurma hemorrhagic fever)',
    'AIDS (Acquired Immune Deficiency Syndrome)',
    'AIDS (Acquired Immunodeficiency Syndrome)',
    'Alkhurma hemorrhagic fever (AHF)',
    'ALS [Amyotrophic Lateral Sclerosis]',
    'Alzheimer\'s Disease',
    'Amebiasis, Intestinal [Entamoeba histolytica infection]',
    'American Indian and Alaska Native Vaccination',
    'American Trypanosomiasis',
    'Amphibians and Fish, Infections from',
    'Amyotrophic Lateral Sclerosis',
    'Anaplasmosis, Human',
    'Ancylostoma duodenale Infection, Necator americanus Infection',
    'Angiostrongylus Infection',
    'Animal-Related Diseases',
    'Anisakiasis',
    'Anisakis Infection [Anisakiasis]',
    'Anthrax [Bacillus anthracis Infection]',
    'Antibiotic and Antimicrobial Resistance',
    'Antibiotic Use, Appropriate',
    'Aortic Aneurysm',
    'Aortic Dissection',
    'Arenavirus Infection',
    'Arthritis',
    'Childhood Arthritis',
    'Fibromyalgia',
    'Gout',
    'Osteoarthritis (OA)',
    'Rheumatoid Arthritis (RA)',
    'Ascariasis',
    'Ascaris Infection [Ascariasis]',
    'Aseptic Meningitis',
    'Aspergillosis',
    'Aspergillus Infection [Aspergillosis]',
    'Asthma',
    'Attention Deficit/Hyperactivity Disorder',
    'Autism',
    'Avian Influenza',
    'B virus Infection [Herpes B virus]',
    'B. cepacia infection (Burkholderia cepacia Infection)',
    'Babesia Infection',
    'Babesiosis [Babesia Infection]',
    'Bacillus anthracis',
    'Bacillus anthracis Infection',
    'Back Belts',
    'Bacterial Meningitis',
    'Bacterial Vaginosis (BV)',
    'Balamuthia mandrillaris Infection',
    'Balamuthia Infection [Balamuthia mandrillaris Infection]',
    'Balantidiasis',
    'Balantidium Infection [Balantidiasis]',
    'Bartonella bacilliformis Infection',
    'Bartonella quintana Infection',
    'Baylisascaris Infection',
    'BCG (Tuberculosis Vaccine)',
    'Bilharzia',
    'Bioterrorism Agents/Diseases',
    'Bird Flu',
    'Birth Defects',
    'Black Lung [Coal Workers Pneumoconioses]',
    'Blast Injuries',
    'Blastocystis hominis Infection',
    'Blastocystis Infection [Blastocystis hominis Infection]',
    'Bleeding Disorders',
    'blood clot',
    'Blood Disorders',
    'Body Lice [Pediculus humanus corporis]',
    'Borrelia burgdorferi Infection',
    'Botulism [Clostridium botulinim Infection]',
    'Bovine Spongiform Encephalopathy (BSE)',
    'Brainerd Diarrhea',
    'Breast and Ovarian Cancer and Family Health History',
    'Breast Cancer',
    'Breastfeeding',
    'Bronchiolitis',
    'Bronchitis',
    'Brucella Infection [Brucellosis]',
    'Brucellosis',
    'BSE (Bovine Spongiform Encephalopathy)',
    'BSE (Mad Cow Disease)',
    'Burkholderia cepacia Infection (B. cepacia infection)',
    'Burkholderia mallei',
    'Burkholderia pseudomallei Infection',
    'BV (Bacterial Vaginosis)',
    'C. diff. Infection [Clostridium difficile Infection]',
    'C. gattii cryptococcosis',
    'C. neoformans cryptococcosis',
    'Campylobacter Infection [Campylobacteriosis]',
    'Campylobacteriosis',
    'Cancer',
    'Colorectal (Colon) Cancer',
    'Gynecologic Cancers',
    'Lung Cancer',
    'Prostate Cancer',
    'skin Cancer',
    'Cancer and Flu',
    'Cancer Health Disparities',
    'Candida Infection [Candidiasis]',
    'Genital Candidiasis (VVC) [Vulvovaginal Candidiasis]',
    'Invasive Candidiasis',
    'Thrush [Oropharyngeal Candidiasis]',
    'Candidiasis',
    'Canine Flu',
    'Capillaria Infection [Capillariasis]',
    'Capillariasis',
    'Carbapenem resistant Klebsiella pneumonia  (CRKP)',
    'Carbapenem-resistant Enterobacteriaceae (CRE)',
    'Cardiovascular Health',
    'Carpal Tunnel Syndrome',
    'Carrión’s disease [Bartonella bacilliformis Infection]',
    'Cat Flea Tapeworm',
    'Cat Scratch Disease from Pets',
    'Cats, Infections from',
    'CCHF (Crimean-Congo hemorrhagic fever)',
    'Cercarial Dermatitis',
    'Cerebral Palsy',
    'Cervical Cancer',
    'CFS (Chronic Fatigue Syndrome)',
    'Chagas Disease [Trypanosoma cruzi Infection]',
    'Chapare Hemorrhagic Fever (CHHF)',
    'Chest Cold',
    'CHHF (Chapare Hemorrhagic Fever)',
    'Chickenpox [Varicella Disease]',
    'Chickenpox Vaccination',
    'Chikungunya Fever (CHIKV)',
    'CHIKV (Chikungunya Fever)',
    'Childhood Arthritis',
    'Childhood Injuries',
    'Childhood Overweight and Obesity',
    'Children\'s Cough and Cold Medicines',
    'Chlamydia [Chlamydia trachomatis Disease]',
    'Chlamydia trachomatis Disease',
    'Chlamydophila (Chlamydia) pneumoniae Infection',
    'Cholera [Vibrio cholerae Infection]',
    'Chronic Disease Prevention',
    'Chronic Fatigue Syndrome (CFS)',
    'Chronic Kidney Disease (CKD)',
    'Chronic Obstructive Pulmonary Disease (COPD)',
    'Chronic Wasting Disease (CWD)',
    'Ciguatera Fish Poisoning',
    'Ciguatoxin',
    'CJD, Classic (Classic Creutzfeldt-Jakob Disease)',
    'CKD (Chronic Kidney Disease)',
    'CKD (Kidney Disease)',
    'Classic Creutzfeldt-Jakob Disease (CJD, Classic)',
    'Clonorchiasis',
    'Clonorchis Infection [Clonorchiasis]',
    'Clostridium botulinim Infection',
    'Clostridium difficile Infection',
    'Clostridium perfringens infection',
    'Clostridium tetani Infection',
    'Clotting Disorders',
    'CMV (Cytomegalovirus Infection)',
    'Coal Workers Pneumoconioses',
    'Coccidioidomycosis',
    'Cold, Common',
    'Colorado Tick Fever (CTF)',
    'Colorectal (Colon) Cancer',
    'Colorectal Cancer Control Program (CRCCP)',
    'Colorectal Cancer and Genetics',
    'Common Cold',
    'Concussion',
    'Congenital Hearing Loss',
    'Conjunctivitis',
    'Cooley\'s Anemia',
    'COPD (Chronic Obstructive Pulmonary Disease)',
    'Corynebacterium diphtheriae Infection',
    'Cough and Cold Medicines',
    'Coxiella burnetii Infection',
    'CRE (Carbapenem-resistant Enterobacteriaceae)',
    'Creutzfeldt-Jakob Disease, Classic',
    'Crimean-Congo hemorrhagic fever (CCHF) [Nairovirus Infection]',
    'CRKP (Carbapenem resistant Klebsiella pneumonia )',
    'Crohn’s Disease',
    'Cronobacter Infection',
    'Cryptococcosis, C. gattii.',
    'Cryptococcosis, C. neoformans',
    'Cryptosporidiosis',
    'Cryptosporidium Infection [Cryptosporidiosis]',
    'CTF (Colorado Tick Fever)',
    'CWD (Chronic Wasting Disease)',
    'Cyclospora Infection [Cyclosporiasis]',
    'Cyclosporiasis',
    'Cysticercosis',
    'Cystoisospora Infection [Cystoisosporiasis]',
    'Cystoisosporiasis',
    'Cytomegalovirus Infection (CMV)',
    'DBA (Diamond Blackfan Anemia)',
    'Death, Leading Causes of Death in Males',
    'Deep Vein Thrombosis (DVT)',
    'Dengue Fever (DF)',
    'Dengue Hemorrhagic Fever (DHF)',
    'Dermatophyte Infection',
    'Developmental Disabilities',
    'DF (Dengue Fever)',
    'DHF (Dengue Hemorrhagic Fever)',
    'Diabetes',
    'Diamond Blackfan Anemia (DBA)',
    'Dientamoeba fragilis Infection',
    'Diet and Nutrition',
    'Diphtheria [Corynebacterium diphtheriae Infection]',
    'Diphtheria Vaccination',
    'Diphyllobothriasis',
    'Diphyllobothrium Infection [Diphyllobothriasis]',
    'Dipylidium Infection',
    'Dirofilariasis (Dog Heartworm)',
    'Division of Public Health Systems and Workforce Development (DPHSWD)',
    'Division of Public Health Systems and Workforce Development (DPHSWD)',
    'Dog Bites',
    'Dog Flea Tapeworm',
    'Dog Heartworm [Dirofilaria]',
    'Dogs, Infections from',
    'Down Syndrome [Trisomy 21]',
    'DPHSWD (Division of Public Health Systems and Workforce Development)',
    'Dracunculiasis',
    'Drug Resistance',
    'DVT (Deep Vein Thrombosis)',
    'Dwarf Tapeworm [Hymenolepis Infection]',
    'E. coli Infection [Escherichia coli Infection]',
    'Ear Infection [Otitis Media]',
    'Early Hearing Detection and Intervention (EHDI)',
    'Eastern Equine Encephalitis (EEE)',
    'Ebola Virus Disease (EVD)',
    'EBV Infection (Epstein-Barr Virus Infection)',
    'Echinococcosis',
    'EEE (Eastern Equine Encephalitis)',
    'EHDI (Early Hearing Detection and Intervention)',
    'Ehrlichiosis, Human',
    'Elephantiasis',
    'Emerging Infectious Diseases',
    'Endophthalmitis, Fungal',
    'Entamoeba histolytica infection',
    'Enteric Diseases from Animals',
    'Enterobius vermicularis Infection',
    'Enterovirus D68',
    'Enterovirus Infections (Non-Polio)',
    'Epidemic Typhus',
    'Epilepsy',
    'Epstein-Barr Virus Infection (EBV Infection)',
    'Ergonomic and Musculoskeletal Disorders',
    'Escherichia coli Infection',
    'Esophageal Candidiasis',
    'EV-D68',
    'EVD (Ebola Virus Disease)',
    'Exserohilum rostratum (Other Pathogenic Fungi)',
    'Extensively Drug-Resistant TB (XDR TB)',
    'Extreme Cold [Hypothermia]',
    'Extreme Heat [Hyperthermia]',
    'x',
    'Falls from Elevation',
    'Falls, Older Adults',
    'Family Health',
    'Family Health History',
    'Family Health History and Breast and Ovarian Cancer',
    'Farm Animals, Infections from',
    'Farm Worker Injuries',
    'Fasciitis, Necrotizing',
    'Fasciola Infection [Fascioliasis]',
    'Fascioliasis',
    'Fasciolopsiasis',
    'Fasciolopsis Infection [Fasciolopsiasis]',
    'Fetal Alcohol Spectrum Disorder',
    'FETP',
    'FETP (Field Epidemiology Training Program)',
    'Fibromyalgia',
    'Field Epidemiology Training Program (FETP)',
    'Fifth Disease [Parvovirus B19 Infection]',
    'Filariasis, Lymphatic',
    'Fireworks Injuries',
    'Fish and Amphibians, Infections from',
    'Flavorings-Related Lung Disease',
    'Flu',
    'Flu and Cancer',
    'Flu Vaccination',
    'Flu, Pandemic',
    'Flu, Seasonal',
    'Folliculitis',
    'Food Poisoning',
    'Food-Related Diseases',
    'Clostridium perfringens infection',
    'shigella Infection [Shigellosis]',
    'Clostridium perfringens infection',
    'Foodborne Illness',
    'Fragile X Syndrome (FXS)',
    'Francisella tularensis Infection',
    'Fungal diseases [Mycotic diseases]',
    'C. gattii cryptococcosis',
    'C. neoformans cryptococcosis',
    'Candida Infection [Candidiasis]',
    'Histoplasma capsulatum Infection [Histoplasmosis]',
    'Aspergillus Infection [Aspergillosis]',
    'Blastomycosis [Blastomyces dermatitidis  Infection]',
    'Blastomycosis [Blastomyces dermatitidis infection]',
    'Fungal Eye Infections',
    'Histoplasmosis [Histoplasma capsulatum Infection]',
    'Mucormycosis',
    'Pneumocystis pneumonia (PCP) [Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii) ]',
    'Ringworm [Dermatophyte Infection]',
    'sporotrichosis',
    'sporotrichosis [Sporothrix schenckii infection]',
    'Valley Fever [Coccidioidomycosis]',
    'Fungal Eye Infections',
    'Fungal Meningitis',
    'Fungal Pneumonia',
    'FXS (Fragile X Syndrome)',
    'GAE  (Acanthamoe (Granulomatous Amebic Encephalitis (Acanthamoeba))',
    'GAE (Granulomatous amebic encephalitis)',
    'GAS (Group A Strep Infection)',
    'Gastrointestinal Diseases from Animals [Zoonotic enteric diseases]',
    'GBS (Group B Strep Infection)',
    'GBS and Menactra Meningococcal Vaccine',
    'GDDER (Global Disease Detection and Emergency Response)',
    'Genetics and Colorectal Cancer',
    'Genetics and Heart Disease',
    'Genetics and Mental Health',
    'Genetics and Obesity',
    'Genetics and Skin Cancer',
    'Genetics and Stroke',
    'Genital Candidiasis (VVC) [Vulvovaginal Candidiasis]',
    'Genital Herpes [Herpes Simplex Virus Infection]',
    'Genital Warts',
    'German Measles (Rubella Virus)',
    'Giardia Infection [Giardiasis]',
    'Giardiasis',
    'Glanders [Burkholderia mallei]',
    'Global Disease Detection and Emergency Response (GDDER)',
    'Global Health Security',
    'Global Measles Elimination',
    'Gnathostoma Infection',
    'Gnathostomiasis [Gnathostoma Infection]',
    'Gonorrhea [Neisseria gonorrhoeae Infection]',
    'Gout',
    'Granulomatous amebic encephalitis (GAE)',
    'Granulomatous Amebic Encephalitis (Acanthamoeba) (GAE  (Acanthamoe)',
    'Group A Strep Infection (GAS) [Group A Streptococcal Infection]',
    'Group A Streptococcal Infection',
    'Group B Strep Infection (GBS) [Group B Streptococcal Infection]',
    'Group B Streptococcal Infection',
    'Guillain-Barré Syndrome and Menactra Meningococcal Vaccine',
    'Guinea Worm Disease [Dracunculiasis]',
    'Gynecologic Cancers',
    'Cervical Cancer',
    'Ovarian Cancer',
    'Uterine Cancer',
    'Vaginal and Vulvar Cancers',
    'H3N2v influenza',
    'H5N1',
    'Haemophilus influenzae Infection (including Hib Infection)',
    'Haemophilus influenzae Serotype b',
    'Hand, Foot, and Mouth Disease (HFMD)',
    'Hansen\'s Disease',
    'Hantavirus Pulmonary Syndrome (HPS)',
    'Hazardous Drug Exposures in Healthcare',
    'Head Lice [Pediculus humanus capitis]',
    'Health Disparities in Cancer',
    'Health Disparities in HIV/AIDS, Viral Hepatitis, STDs, and TB',
    'Health Security',
    'Healthcare Associated Infections',
    'surgical site infection (SSI)',
    'Healthy Pets, Healthy People',
    'Healthy Weight',
    'Hearing Loss in Children',
    'Hearing, Early Detection & Intervention',
    'Heart Disease [Cardiovascular Health]',
    'Heart Disease and Genetics',
    'Heat Stress',
    'Hemochromatosis',
    'Hemoglobinopathies',
    'Hemophilia',
    'Hemophilia Treatment Centers (HTC)',
    'Hemorrhagic Fevers, Viral',
    'Hendra Virus Disease (HeV Infection)',
    'Hepatitis A Vaccination',
    'Hepatitis B Vaccination',
    'Hepatitis, Viral',
    'Hereditary Bleeding Disorders',
    'Herpes B virus',
    'Herpes Simplex Virus Infection',
    'Herpes Zoster',
    'Herpes Zoster Vaccination',
    'Herpes, Genital',
    'Herpesvirus B',
    'Herpesvirus simiae',
    'Heterophyes Infection [Heterophyiasis]',
    'Heterophyiasis',
    'HeV Infection (Hendra Virus Disease)',
    'HFMD (Hand, Foot, and Mouth Disease)',
    'Hib Infection [Haemophilus influenzae Serotype b]',
    'Hib Vaccine (Haemophilus influenzae Serotype b Vaccination)',
    'High Blood Pressure',
    'Histoplasma capsulatum Infection [Histoplasmosis]',
    'Histoplasmosis',
    'HIV/AIDS',
    'HIV/AIDS and STDs',
    'Hookworm, Human [Ancylostoma duodenale Infection, Necator americanus Infection]',
    'Hookworm, Zoonotic',
    'Horses, Infections from',
    'Hot Tub Rash [Pseudomonas dermatitis Infection]',
    'HPIV (Human Parainfluenza Viruses)',
    'HPS (Hantavirus Pulmonary Syndrome)',
    'HPV Infection (Human Papillomavirus Infection)',
    'HPV Vaccination (Human Papillomavirus Vaccination)',
    'HPV-Associated Cancers',
    'HTC (Hemophilia Treatment Centers)',
    'Human Ehrlichiosis',
    'Human Hookworm [Ancylostoma duodenale Infection, Necator americanus Infection]',
    'Human Immunodeficiency Virus',
    'Human Papillomavirus Infection (HPV Infection)',
    'Human Papillomavirus Vaccination (HPV Vaccination)',
    'Human Parainfluenza Viruses (HPIV)',
    'Hymenolepis Infection',
    'Hypertension',
    'Hyperthermia',
    'Hypothermia',
    'IBD (Inflammatory Bowel Disease)',
    'IMMPaCt (International Micronutrient Malnutrition Prevention and Control Program)',
    'Impetigo',
    'including Hib Infection (Haemophilus influenzae Infection)',
    'Infectious Mononucleosis',
    'Infertility',
    'Inflammatory Bowel Disease (IBD)',
    'Influenza',
    'H1N1 Flu',
    'People at High Risk',
    'seasonal Flu',
    'swine Influenza',
    'Influenza and Cancer',
    'Influenza in Pigs',
    'Influenza Vaccination',
    'Influenza, Avian',
    'Influenza, Pandemic',
    'Injury, Healthy Swimming and Recreational Water',
    'International Micronutrient Malnutrition Prevention & Control Program (IMMPaCt)',
    'Intestinal Amebae Infection, Nonpathogenic',
    'Invasive Candidiasis',
    'Iron Overload [Hemochromatosis]',
    'Iron Storage Disease',
    'Isospora Infection [Isosporiasis]',
    'Japanese Encephalitis (JE)',
    'Japanese Encephalitis (JE) Vaccination',
    'Jaundice',
    'JE (Japanese Encephalitis)',
    'JE (Japanese Encephalitis) Vaccination',
    'K. pneumoniae (Klebsiella pneumoniae)',
    'Kala-Azar',
    'Kawasaki Disease (KD)',
    'Kawasaki Syndrome',
    'KD (Kawasaki Disease)',
    'Keratitis, Acanthamoeba',
    'Keratitis, Fungal',
    'Kernicterus',
    'KFD (Kyasanur Forest disease)',
    'Kidney Disease (CKD)',
    'Klebsiella pneumoniae (K. pneumoniae)',
    'Kyasanur Forest disease (KFD)',
    'La Crosse Encephalitis (LAC)',
    'La Crosse Encephalitis virus (LACV)',
    'LAC (La Crosse Encephalitis)',
    'LACV (La Crosse Encephalitis virus)',
    'Lassa Fever',
    'Latex Allergies',
    'LCM (Lymphocytic Choriomeningitis)',
    'Lead Poisoning',
    'Legionellosis',
    'Legionnaires Disease [Legionellosis]',
    'Leishmania Infection [Leishmaniasis]',
    'Leishmaniasis',
    'Leprosy',
    'Leptospira Infection [Leptospirosis]',
    'Leptospirosis',
    'Lice',
    'Lice, Body',
    'Lice, Head',
    'Lice, Pubic',
    'Listeria Infection [Listeriosis]',
    'Listeriosis',
    'Liver Disease and Hepatitis',
    'Loa loa Infection',
    'Lockjaw',
    'Lockjaw Vaccination',
    'Loiasis [Loa loa Infection]',
    'Lou Gehrig\'s Disease',
    'LUHF (Lujo Hemorrhagic Fever)',
    'Lujo Hemorrhagic Fever (LUHF)',
    'Lung Cancer',
    'Lupus (SLE) [Systemic lupus erythematosus]',
    'Lyme Disease [Borrelia burgdorferi Infection]',
    'Lymphatic Filariasis',
    'Lymphedema',
    'Lymphocytic Choriomeningitis (LCM)',
    'MAC (Mycobacterium avium Complex)',
    'Mad Cow Disease (BSE)',
    'Malaria',
    'Marburg Hemorrhagic Fever',
    'Marine Toxins',
    'MD (Muscular Dystrophy)',
    'MDR TB (Multidrug-Resistant TB)',
    'Measles',
    'Measles Vaccination',
    'Melioidosis [Burkholderia pseudomallei Infection]',
    'Men\'s Health',
    'Meningitis',
    'Meningococcal Disease',
    'Meningococcal Vaccination',
    'Mental Health',
    'Mental Health and Genetics',
    'Mental Retardation',
    'MERS-CoV (Middle East Respiratory Syndrome Coronavirus)',
    'Methicillin Resistant Staphylococcus aureus',
    'Microcephaly',
    'Micronutrient Malnutrition',
    'Microsporidia Infection',
    'Middle East Respiratory Syndrome Coronavirus (MERS-CoV)',
    'MMR Vaccination',
    'Molluscum Contagiosum',
    'Monkey B virus',
    'Monkeypox',
    'Monkeypox Vaccination',
    'Mononucleosis, Infectious',
    'Motor Vehicle Injuries',
    'Mouse and Rat Control',
    'MRSA [Methicillin Resistant Staphylococcus aureus]',
    'Mucormycosis',
    'Mucus',
    'Multidrug-Resistant TB (MDR TB)',
    'Multiple organ dysfunction syndrome',
    'Mumps',
    'Mumps Vaccination',
    'Muscular Dystrophy (MD)',
    'Musculoskeletal Disorders',
    'Mycobacterium abscessus Infection',
    'Mycobacterium avium Complex (MAC)',
    'Mycobacterium tuberculosis Infection',
    'Mycoplasma pneumoniae Infection',
    'Mycotic diseases',
    'Myelomeningocele',
    'Myiasis',
    'Naegleria Infection [Primary Amebic Meningoencephalitis (PAM)]',
    'Nairovirus Infection',
    'National Amyotrophic Lateral Sclerosis (ALS) Registry',
    'Necrotizing Fasciitis',
    'Neglected Tropical Diseases (NTD)',
    'Neisseria gonorrhoeae Infection',
    'Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii) ',
    'Neurocysticercosis',
    'Newborn Hearing',
    'Newborn Jaundice [Kernicterus]',
    'Nocardia asteroides Infection',
    'Nocardiosis [Nocardia asteroides Infection]',
    'Non-Polio Enterovirus Infections',
    'Nonpathogenic (Harmless) Intestinal Protozoa',
    'Norovirus Infection',
    'Norwalk-like Viruses (NLV)',
    'NTD (Neglected Tropical Diseases)',
    'Nutrition',
    'OA (Osteoarthritis)',
    'Obesity and Genetics',
    'Obesity and Overweight',
    'Obesity and Overweight, Childhood',
    'Occupational Cancers',
    'Occupational Skin Conditions',
    'Occupational Stress',
    'OHF (Omsk hemorrhagic fever)',
    'Omsk hemorrhagic fever (OHF)',
    'Onchocerciasis',
    'Opisthorchis Infection',
    'Oral Cancer',
    'Orf Virus Infection',
    'Oropharyngeal Candidiasis',
    'Oroya fever',
    'Osteoarthritis (OA)',
    'Otitis Media',
    'Outbreaks',
    'Ovarian and Breast Cancer and Family Health History',
    'Ovarian Cancer',
    'Overweight and Obesity',
    'Overweight and Obesity, Childhood',
    'PAD (Peripheral Arterial Disease)',
    'Pandemic Flu',
    'Paragonimiasis',
    'Paragonimus Infection [Paragonimiasis]',
    'Parainfluenza',
    'Parasitic Diseases',
    'Parvovirus B19 Infection',
    'PCP (Pneumocystis pneumonia)',
    'PCV (Pneumococcal Conjugate Vaccine)',
    'PE (Pulmonary Embolism)',
    'Pedestrian Injury',
    'Pediculus humanus capitis',
    'Pediculus humanus corporis',
    'Pelvic Inflammatory Disease (PID)',
    'Peripheral Arterial Disease (PAD)',
    'Peripheral Arterial Insufficiency',
    'Peripheral Arterial Occlusive Disease',
    'Peripheral Vascular Disease',
    'Pertussis (Whooping Cough)',
    'Pertussis (Whooping Cough) Vaccination',
    'Pet-Related Diseases',
    'Phthiriasis',
    'PID (Pelvic Inflammatory Disease)',
    'Pigs, Influenza in',
    'Pink Eye [Conjunctivitis]',
    'Pinworm Infection [Enterobius vermicularis Infection]',
    'Plague [Yersinia pestis Infection]',
    'Pneumococcal Conjugate Vaccine (PCV)',
    'Pneumococcal Disease',
    'Pneumococcal Polysaccharide Vaccine (PPV)',
    'Pneumoconioses, Coal Workers',
    'Pneumocystis carinii Pneumonia (PCP) Infection',
    'Pneumocystis pneumonia (PCP) [Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii) ]',
    'Pneumonia',
    'Polio Infection [Poliomyelitis Infection]',
    'Polio Vaccination [Poliomyelitis Vaccination]',
    'Poliomyelitis Infection',
    'Poliomyelitis Vaccination',
    'Pontiac Fever',
    'Powassan (POW) virus',
    'Poxvirus Infections',
    'PPV (Pneumococcal Polysaccharide Vaccine)',
    'Pregnancy',
    'Primary Amebic Meningoencephalitis (PAM)',
    'Prion Diseases (TSEs) [Transmissible spongiform encephalopathies]',
    'Prostate Cancer',
    'Pseudomonas dermatitis Infection',
    'Psittacosis',
    'Psoriasis',
    'Pubic Lice [Phthiriasis]',
    'Pulmonary Embolism (PE)',
    'Pulmonary Hypertension',
    'Q Fever [Coxiella burnetii Infection]',
    'RA (Rheumatoid Arthritis)',
    'Rabies',
    'Rabies Vaccination',
    'Raccoon Roundworm Infection [Baylisascaris Infection]',
    'Rat-Bite Fever (RBF) [Streptobacillus moniliformis Infection]',
    'RBF (Rat-Bite Fever)',
    'Recalled Vaccines',
    'Recreational Water Illness (RWI)',
    'Reptiles, Infections from',
    'Respiratory Syncytial Virus Infection (RSV)',
    'Rheumatoid Arthritis (RA)',
    'Rickettsia rickettsii Infection',
    'Rickettsia, Spotted Fever Group',
    'Rickettsial Diseases',
    'Rift Valley Fever (RVF)',
    'Ringworm [Dermatophyte Infection]',
    'Ringworm from Animals',
    'River Blindness [Onchocerciasis]',
    'RMSF (Rocky Mountain Spotted Fever)',
    'Rocky Mountain Spotted Fever (RMSF) [Rickettsia rickettsii Infection]',
    'Rodent Control',
    'Rodents',
    'Rodents, Diseases from',
    'Rotavirus Infection',
    'Rotavirus Vaccination',
    'RSV (Respiratory Syncytial Virus Infection)',
    'Rubella (German Measles) Vaccination',
    'Rubeola',
    'Runny Nose',
    'RVF (Rift Valley Fever)',
    'RWI (Recreational Water Illness)',
    'salmonella typhi Infection',
    'salmonella Infection [Salmonellosis]',
    'salmonella Infection from Animals',
    'salmonellosis',
    'salt',
    'sappinia diploidea and Sappinia pedata',
    'sappinia Infection [Sappinia diploidea and Sappinia pedata]',
    'sARS [Severe Acute Respiratory Syndrome]',
    'scabies',
    'scarlet Fever',
    'schistosoma Infection',
    'schistosomiasis [Schistosoma Infection]',
    'seasonal Flu',
    'sepsis [Septicemia]',
    'septic shock',
    'septicemia',
    'severe Acute Respiratory Syndrome',
    'sexually Transmitted Disease Surveillance Reports',
    'sexually Transmitted Diseases (STDs)',
    'Bacterial Vaginosis (BV)',
    'Chlamydia [Chlamydia trachomatis Disease]',
    'Genital Herpes [Herpes Simplex Virus Infection]',
    'Gonorrhea [Neisseria gonorrhoeae Infection]',
    'Human Papillomavirus Infection (HPV Infection)',
    'Pelvic Inflammatory Disease (PID)',
    'syphilis [Treponema pallidum Infection]',
    'Trichomoniasis [Trichomonas Infection]',
    'sFGR (Spotted Fever Group Rickettsia)',
    'shigella Infection [Shigellosis]',
    'shigellosis',
    'shingles [Varicella Zoster Virus (VZV)]',
    'shingles Vaccination',
    'sickle Cell Disease',
    'sIDS (Sudden Infant Death Syndrome)',
    'sinus Infection [Sinusitus]',
    'sinusitus',
    'skin Cancer',
    'skin Cancer and Genetics',
    'skin Conditions, Occupational',
    'sLE (Lupus)',
    'sleep and Sleep Disorders',
    'sleeping Sickness [African Trypanosomiasis]',
    'smallpox [Variola Major and Variola Minor]',
    'smallpox Vaccination',
    'smoking and Tobacco Use',
    'sodium',
    'soil Transmitted Helminths',
    'sore Mouth Infection [Orf Virus Infection]',
    'sore Throat',
    'southern Tick-Associated Rash Illness (STARI)',
    'spina Bifida [Myelomeningocele]',
    'spirillum minus Infection',
    'sporothrix schenckii infection',
    'sporotrichosis [Sporothrix schenckii infection]',
    'spotted Fever Group Rickettsia (SFGR)',
    'staph',
    'staphylococcus aureus Infection',
    'sTARI (Southern Tick-Associated Rash Illness)',
    'sTDs (Sexually Transmitted Diseases)',
    'sTDs and HIV/AIDS',
    'strep Infection, Group A',
    'strep Infection, Group B',
    'strep Throat',
    'streptobacillus moniliformis Infection',
    'streptococcus pneumoniae Infection',
    'stress, Occupational',
    'stroke',
    'stroke and Genetics',
    'strongyloidiasis',
    'sudden Infant Death Syndrome (SIDS)',
    'surveillance Reports, Sexually Transmitted Disease',
    'swimmer\'s Itch [Cercarial Dermatitis]',
    'swimming-related Illness',
    'swine Influenza',
    'symptom Relief for Upper Respiratory Infections',
    'syphilis [Treponema pallidum Infection]',
    'systemic lupus erythematosus',
    'Taenia Infection',
    'Tapeworm Infection [Taenia Infection]',
    'Tapeworm, Dog and Cat Flea [Dipylidium Infection]',
    'TB (Tuberculosis)',
    'TB (Tuberculosis) Vaccination',
    'TB and HIV Coinfection',
    'TB and the African-American Communtiy',
    'TB Data & Statistics',
    'TB Education and Training Network',
    'TB in African-Americans',
    'TB Surveillance Reports',
    'TB Testing & Diagnosis',
    'TBI (Traumatic Brain Injury)',
    'Testicular Cancer',
    'Tetanus (Lockjaw) Infection',
    'Tetanus (Lockjaw) Vaccination',
    'Tetanus Disease [Clostridium tetani Infection]',
    'Thalassemia',
    'Thoracic Aortic Aneurysm',
    'Throat, Sore',
    'Throat, Strep',
    'Thrombophilia',
    'Thrombosis',
    'Thrush [Oropharyngeal Candidiasis]',
    'Tickborne Diseases',
    'Ticks',
    'Anaplasmosis, Human',
    'Babesiosis [Babesia Infection]',
    'Ehrlichiosis, Human',
    'Lyme Disease [Borrelia burgdorferi Infection]',
    'Powassan (POW) virus',
    'Rocky Mountain Spotted Fever (RMSF) [Rickettsia rickettsii Infection]',
    'southern Tick-Associated Rash Illness (STARI)',
    'Tularemia [Francisella tularensis Infection]',
    'Tinea',
    'Tobacco Use, Smoking and',
    'Tourette Syndrome  (TS)',
    'Toxocara Infection',
    'Toxocariasis [Toxocara Infection]',
    'Toxoplasma Infection',
    'Toxoplasmosis [Toxoplasma Infection]',
    'Trachoma Infection',
    'Transmissible spongiform encephalopathies',
    'Traumatic Brain Injury (TBI)',
    'Traumatic Occupational Injuries',
    'Trench fever [Bartonella quintana Infection]',
    'Treponema pallidum Infection',
    'Trichinellosis (Trichinosis)',
    'Trichomonas Infection',
    'Trichomoniasis [Trichomonas Infection]',
    'Trichuriasis',
    'Trisomy 21',
    'Trypanosoma cruzi Infection',
    'Trypanosomiasis, African',
    'TS (Tourette Syndrome )',
    'TSEs (Prion Diseases)',
    'Tuberculosis (TB) [Mycobacterium tuberculosis Infection]',
    'Tuberculosis (TB) Vaccination',
    'Tuberculosis and HIV Coinfection',
    'Tuberculosis Skin Test',
    'Tuberculosis Training',
    'Tuberculosis Vaccine (BCG)',
    'Tularemia [Francisella tularensis Infection]',
    'Typhoid Fever [Salmonella typhi Infection]',
    'Typhoid Fever Vaccination',
    'Typhus Fevers',
    'Ulcerative Colitis',
    'Undulant Fever',
    'Unexplained Respiratory Disease Outbreaks (URDO)',
    'Universal Newborn Hearing Screening',
    'Upper Respiratory Infection Symptom Relief',
    'URDO (Unexplained Respiratory Disease Outbreaks)',
    'Uterine Cancer',
    'Vaccination',
    'Vaccination and Pregnancy',
    'Vaccination, American Indian and Alaska Native',
    'Vaccine Adverse Event Reporting System (VAERS)',
    'Vaccine Information Statements (VIS)',
    'Vaccine Ingredients',
    'Vaccine Management System (VACMAN)',
    'Vaccine Recalls, Questions About',
    'Vaccine Safety',
    'Vaccine Safety (Emergency Preparedness)',
    'Vaccine Safety Concerns',
    'Vaccine Safety for Measles, Mumps, Rubella, Varicella (MMRV)',
    'Vaccine Safety, Intussusception and Rotavirus Vaccine',
    'Vaccine Side Effects',
    'Vaccine Tracking System (VTrckS)',
    'Vaccine-Preventable Diseases and Specific Vaccines',
    'Vaccines',
    'Vaccines and Sudden Infant Death Syndrome (SIDS)',
    'Vaccines and Thimerosal (Mercury)',
    'Vaccines for Children Program',
    'Vaccines, Testing and Monitoring',
    'VACMAN (Vaccine Management System)',
    'VAERS (Vaccine Adverse Event Reporting System)',
    'Vaginal and Vulvar Cancers',
    'Vaginal Candidiasis',
    'Valley Fever [Coccidioidomycosis]',
    'Vancomycin-Intermediate/Resistant Staphylococcus aureus Infections [VISA/VRSA]',
    'Vancomycin-resistant Enterococci Infection (VRE)',
    'VAP (Ventilator-associated pneumonia)',
    'Variant Creutzfeldt-Jakob Disease (vCJD)',
    'Varicella Disease',
    'Varicella Vaccination',
    'Varicella Zoster Virus (VZV)',
    'Varicella-Zoster Virus Infection',
    'Variola Major and Variola Minor',
    'vCJD (Variant Creutzfeldt-Jakob Disease)',
    'Vehicle Safety',
    'Venezuela',
    'Venomous Snakes',
    'Venomous Spiders',
    'Venous Thromboembolism (VTE)',
    'Ventilator-associated pneumonia (VAP)',
    'Vermiculite',
    'verruga peruana',
    'Vessel Sanitation and Health',
    'Veterinary Safety and Health',
    'Veterinary Students, Epidemiology Elective Program for',
    'VFC Program [Vaccines for Children Program]',
    'VHF (Viral Hemorrhagic Fevers)',
    'Vibration',
    'Vibrio cholerae Infection',
    'Vibrio Illness [Vibriosis]',
    'Vibriosis',
    'Video',
    'Vietnam',
    'Violence',
    'Violence, Occupational',
    'Viral Hemorrhagic Fevers (VHF)',
    'Alkhurma hemorrhagic fever (AHF)',
    'Chapare Hemorrhagic Fever (CHHF)',
    'Crimean-Congo hemorrhagic fever (CCHF) [Nairovirus Infection]',
    'Ebola Virus Disease (EVD)',
    'Hantavirus Pulmonary Syndrome (HPS)',
    'Kyasanur Forest disease (KFD)',
    'Lassa Fever',
    'Lujo Hemorrhagic Fever (LUHF)',
    'Marburg Hemorrhagic Fever',
    'Omsk hemorrhagic fever (OHF)',
    'Rift Valley Fever (RVF)',
    'Viral Hepatitis',
    'Viral Meningitis [Aseptic Meningitis]',
    'Virtual Platform Initiative (VPI)',
    'VIS (Vaccine Information Statements)',
    'VISA/VRSA',
    'Vision and Mission, CDC',
    'Vision Health Initiative',
    'Vision Impairment',
    'Visitors Center',
    'Vital and Health Statistics Reports (Rainbow Series)',
    'Vital Records',
    'Vital Signs',
    'Vital Signs Town Hall Conferences',
    'VitalStats',
    'Vitamins',
    'Volcanoes',
    'Von Willebrand Disease',
    'VPD Surveillance Manual',
    'VPI (Virtual Platform Initiative)',
    'VRE (Vancomycin-resistant Enterococci Infection)',
    'VTE (Venous Thromboembolism)',
    'VTrckS (Vaccine Tracking System)',
    'Vulnerable',
    'Vulvovaginal Candidiasis',
    'VVC (Genital Candidiasis)',
    'VWD [Von Willebrand Disease]',
    'VX',
    'VZV (Varicella Zoster Virus)',
    'Weight, Healthy',
    'West Nile Virus Infection (WNV Infection)',
    'Whipworm Infection [Trichuriasis]',
    'Whitmore\'s Disease',
    'Whooping Cough',
    'Whooping Cough (Pertussis) Vaccination',
    'Wildlife, Infections from',
    'Winter Storms',
    'WNV Infection (West Nile Virus Infection)',
    'Women\'s Bleeding Disorders',
    'Women\'s Health',
    'XDR TB (Extensively Drug-Resistant TB)',
    'Xenotropic Murine Leukemia Virus-related Virus Infection',
    'XMRV Infection [Xenotropic Murine Leukemia Virus-related Virus Infection]',
    'Yeast Infection',
    'Yellow Fever',
    'Yellow Fever Vaccination',
    'Yersinia enterocolitica Infection',
    'Yersinia pestis Infection',
    'Yersiniosis [Yersinia enterocolitica Infection]',
    'Zika Virus Infection',
    'Zoonotic Diseases from Animals',
    'Zoonotic enteric diseases',
    'Zoonotic Hookworm',
    'Zoster',
    'Zygomycosis '
  ],
  orgs: [
    'Homo sapiens',
    'Arabidopsis thaliana',
    'Homo neanderthalensis',
    'Proboscidea',
    'Bacillus',
    'reptiles',
    'Agathis montana',
    'Mus musacris'
  ],
  exp: [
    'Expression profiling by array',
    'Expression profiling by high throughput sequencing',
    'Expression profiling by RT-PCR',
    'Genome binding/occupancy profiling by high throughput sequencing',
    'Genome variation profiling by array',
    'Genome variation profiling by genome tiling array',
    'Genome variation profiling by SNP array',
    'Methylation profiling by high throughput sequencing',
    'Non-coding RNA profiling by array',
    'Non-coding RNA profiling by high throughput sequencing',
    'Protein profiling by protein array'
  ]
}
