/**
 * queryOptions configs contains Values to be displayed while making a search
 * to NCBI DB
 */
export const QueryOptions = {
  drugs: [
    'Abacavir Sulfate', 'barelix', 'A`batacept', 'Abciximab', 'Abelcet', 'Abilify', 'Abraxane', 'Acamprosate Calcium', 'Acarbose', 'Accolate', 'Accretropin', 'AccuNeb', 'Accupril', 'Accutane', 'Acebutolol', 'Aceon', 'Acetadote', 'Acetaminophen', 'Acetic Acid', 'Aci- Jel', 'Aciphex', 'Acitretin', 'Aclovate', 'Acrivastine and Pseudoephedrine', 'Actemra', 'Acthrel', 'Acticin', 'Actimmune', 'Actiq', 'Actisite', 'Activase', 'Activella', 'Actonel', 'Actos', 'Acular', 'Acular LS', 'Acuvail', 'Acyclovir', 'Adacel', 'Adagen', 'Adalat CC', 'Adalimumab', 'Adapalene', 'Adcirca', 'Adderall', 'Adderall XR', 'Adefovir Dipivoxil', 'Adenoscan', 'Adenosine', 'Adipex- P', 'Adoxa', 'Adrenalin', 'AdreView', 'Adriamycin PFS', 'Advair Diskus', 'Advair HFA', 'Advicor', 'Aerospan HFA', 'Afinitor', 'Afluria', 'Agalsidase Beta', 'Aggrastat', 'Aggrenox', 'Agrylin', 'Ak- Fluor', 'Akineton', 'Alamast', 'Albendazole', 'Albenza', 'Albumin, Human', 'Albuminar', 'Albuterol Sulfate', 'Albuterol Sulfate Inhalation Aerosol', 'Alcaine', 'Alclometasone Dipropionate', 'Aldactazide', 'Aldactone', 'Aldara', 'Aldesleukin', 'Aldomet', 'Aldoril', 'Aldurazyme', 'Alefacept', 'Alemtuzumab', 'Alendronate Sodium', 'Alesse', 'Alfenta', 'Alfentanil', 'Alfuzosin HCl', 'Alglucosidase Alfa', 'Alimta', 'Alinia', 'Alitretinoin', 'Alkeran', 'Allegra', 'Allegra- D', 'Allegra D 24 Hour', 'Allernaze', 'Alli', 'Allopurinol', 'Almotriptan Malate', 'Alocril', 'Alomide', 'Aloprim', 'Alora', 'Alosetron Hydrochloride', 'Aloxi', 'Alphanate', 'Alprazolam', 'Alprostadil', 'Alrex', 'Alsuma', 'Altabax', 'Altace', 'Alteplase', 'Altocor', 'Altoprev', 'Altretamine', 'Alupent', 'Alvesco', 'Amantadine Hydrochloride', 'Amaryl', 'Ambien', 'Ambien CR', 'Ambisome', 'Amerge', 'Americaine', 'Amevive', 'Amicar', 'Amifostine', 'Amikacin', 'Amikin', 'Amiloride', 'Amiloride and Hydrochlorothiazide', 'Amiloride Hydrochloride', 'Amino Acids', 'Aminocaproic Acid', 'Aminoglutethimide', 'Aminohippurate Sodium', 'Aminolevulinic Acid', 'Aminosalicylic Acid', 'Aminosyn II 8.5%', 'Aminosyn II in Dextrose', 'Amitiza', 'Amitriptyline', 'Amlexanox', 'Amlodipine Besylate', 'Amoxapine', 'Amoxicillin', 'Amoxicillin Clavulanate', 'Amoxil', 'Amphadase', 'Amphetamine', 'Amphotericin B', 'Ampicillin', 'Ampyra', 'Amrix', 'Amyl Nitrite', 'Amytal Sodium', 'Anabolic steroids', 'Anadrol- 50', 'Anafranil', 'Anagrelide', 'Anakinra', 'Anastrozole', 'Ancobon', 'Androderm', 'AndroGel', 'Anectine', 'Angeliq', 'Angiomax', 'Anidulafungin', 'Anisindione', 'Ansaid', 'Antabuse', 'Antara', 'Anthralin', 'Antihemophilic Factor', 'Antithrombin', 'Antivenin', 'Antivert', 'Antizol', 'Anturane', 'Anusol Hc', 'Aphthasol', 'Apidra', 'Aplenzin', 'Apokyn', 'Apomorphine', 'Apraclonidine', 'Apresazide', 'Apresoline', 'Apri', 'Apriso', 'Aprotinin', 'Aptivus', 'Aquasol A', 'Aralen', 'Aramine', 'Aranesp', 'Arava', 'Arcalyst', 'Aredia', 'Argatroban', 'Aricept', 'Arimidex', 'Aripiprazole', 'Aristocort', 'Arixtra', 'Armodafinil', 'Aromasin', 'Arranon', 'Artane', 'Arthrotec', 'Arzerra', 'Asacol', 'Asacol HD', 'Asclera', 'Ascorbic Acid', 'Asmanex Twisthaler', 'Asparaginase', 'Aspirin', 'Astelin', 'Astemizole', 'Astepro', 'Atacand', 'Atacand HCT', 'Atazanavir Sulfate', 'Atenolol and Chlorthalidone', 'Atgam', 'Ativan', 'Atomoxetine HCl', 'Atorvastatin Calcium', 'Atovaquone', 'Atracurium Besylate', 'Atralin', 'Atridox', 'Atripla', 'Atromid- S', 'Atropen', 'Atropine', 'Atrovent HFA', 'Atryn', 'Augmentin', 'Augmentin XR', 'Auralgan', 'Avage', 'Avalide', 'Avandamet', 'Avandaryl', 'Avandia', 'Avapro', 'Avastin', 'Avelox', 'Avinza', 'Avodart', 'Avonex', 'Axert', 'Axid', 'Aygestin', 'Azacitidine', 'Azasan', 'Azasite', 'Azathioprine', 'Azelaic Acid', 'Azelastine Hydrochloride', 'Azelex', 'Azilect', 'Azithromycin', 'Azmacort', 'Azopt', 'Azor', 'Azulfidine EN- Tabs'
  ],
  diseases: [
    'Abdominal Aortic Aneurysm',
'Acanthamoeba Infection',
'ACE (Adverse Childhood Experiences)',
'Acinetobacter Infection',
'Acquired Immune Deficiency Syndrome (AIDS)',
'Acquired Immunodeficiency Syndrome (AIDS)',
'Adenovirus Infection',
'Adenovirus Vaccination',
'ADHD [Attention Deficit/Hyperactivity Disorder]',
'Adult Vaccinations',
'Adverse Childhood Experiences (ACE)',
'African Trypanosomiasis',
'Agricultural Safety',
'AHF (Alkhurma hemorrhagic fever)',
'AIDS (Acquired Immune Deficiency Syndrome)',
'AIDS (Acquired Immunodeficiency Syndrome)',
'Alkhurma hemorrhagic fever (AHF)',
'ALS [Amyotrophic Lateral Sclerosis]',
'Alzheimer\'s Disease',
'Amebiasis, Intestinal [Entamoeba histolytica infection]',
'American Indian and Alaska Native Vaccination',
'American Trypanosomiasis',
'Amphibians and Fish, Infections from',
'Amyotrophic Lateral Sclerosis',
'Anaplasmosis, Human',
'Ancylostoma duodenale Infection, Necator americanus Infection',
'Angiostrongylus Infection',
'Animal-Related Diseases',
'Anisakiasis',
'Anisakis Infection [Anisakiasis]',
'Anthrax [Bacillus anthracis Infection]',
'Antibiotic and Antimicrobial Resistance',
'Antibiotic Use, Appropriate',
'Aortic Aneurysm',
'Aortic Dissection',
'Arenavirus Infection',
'Arthritis',
'Childhood Arthritis',
'Fibromyalgia',
'Gout',
'Osteoarthritis (OA)',
'Rheumatoid Arthritis (RA)',
'Ascariasis',
'Ascaris Infection [Ascariasis]',
'Aseptic Meningitis',
'Aspergillosis',
'Aspergillus Infection [Aspergillosis]',
'Asthma',
'Attention Deficit/Hyperactivity Disorder',
'Autism',
'Avian Influenza',
'B virus Infection [Herpes B virus]',
'B. cepacia infection (Burkholderia cepacia Infection)',
'Babesia Infection',
'Babesiosis [Babesia Infection]',
'Bacillus anthracis',
'Bacillus anthracis Infection',
'Back Belts',
'Bacterial Meningitis',
'Bacterial Vaginosis (BV)',
'Balamuthia mandrillaris Infection',
'Balamuthia Infection [Balamuthia mandrillaris Infection]',
'Balantidiasis',
'Balantidium Infection [Balantidiasis]',
'Bartonella bacilliformis Infection',
'Bartonella quintana Infection',
'Baylisascaris Infection',
'BCG (Tuberculosis Vaccine)',
'Bilharzia',
'Bioterrorism Agents/Diseases',
'Bird Flu',
'Birth Defects',
'Black Lung [Coal Workers Pneumoconioses]',
'Blast Injuries',
'Blastocystis hominis Infection',
'Blastocystis Infection [Blastocystis hominis Infection]',
'Bleeding Disorders',
'blood clot',
'Blood Disorders',
'Body Lice [Pediculus humanus corporis]',
'Borrelia burgdorferi Infection',
'Botulism [Clostridium botulinim Infection]',
'Bovine Spongiform Encephalopathy (BSE)',
'Brainerd Diarrhea',
'Breast and Ovarian Cancer and Family Health History',
'Breast Cancer',
'Breastfeeding',
'Bronchiolitis',
'Bronchitis',
'Brucella Infection [Brucellosis]',
'Brucellosis',
'BSE (Bovine Spongiform Encephalopathy)',
'BSE (Mad Cow Disease)',
'Burkholderia cepacia Infection (B. cepacia infection)',
'Burkholderia mallei',
'Burkholderia pseudomallei Infection',
'BV (Bacterial Vaginosis)',
'C. diff. Infection [Clostridium difficile Infection]',
'C. gattii cryptococcosis',
'C. neoformans cryptococcosis',
'Campylobacter Infection [Campylobacteriosis]',
'Campylobacteriosis',
'Cancer',
'Colorectal (Colon) Cancer',
'Gynecologic Cancers',
'Lung Cancer',
'Prostate Cancer',
'skin Cancer',
'Cancer and Flu',
'Cancer Health Disparities',
'Candida Infection [Candidiasis]',
'Genital Candidiasis (VVC) [Vulvovaginal Candidiasis]',
'Invasive Candidiasis',
'Thrush [Oropharyngeal Candidiasis]',
'Candidiasis',
'Canine Flu',
'Capillaria Infection [Capillariasis]',
'Capillariasis',
'Carbapenem resistant Klebsiella pneumonia  (CRKP)',
'Carbapenem-resistant Enterobacteriaceae (CRE)',
'Cardiovascular Health',
'Carpal Tunnel Syndrome',
'Carrión’s disease [Bartonella bacilliformis Infection]',
'Cat Flea Tapeworm',
'Cat Scratch Disease from Pets',
'Cats, Infections from',
'CCHF (Crimean-Congo hemorrhagic fever)',
'Cercarial Dermatitis',
'Cerebral Palsy',
'Cervical Cancer',
'CFS (Chronic Fatigue Syndrome)',
'Chagas Disease [Trypanosoma cruzi Infection]',
'Chapare Hemorrhagic Fever (CHHF)',
'Chest Cold',
'CHHF (Chapare Hemorrhagic Fever)',
'Chickenpox [Varicella Disease]',
'Chickenpox Vaccination',
'Chikungunya Fever (CHIKV)',
'CHIKV (Chikungunya Fever)',
'Childhood Arthritis',
'Childhood Injuries',
'Childhood Overweight and Obesity',
'Children\'s Cough and Cold Medicines',
'Chlamydia [Chlamydia trachomatis Disease]',
'Chlamydia trachomatis Disease',
'Chlamydophila (Chlamydia) pneumoniae Infection',
'Cholera [Vibrio cholerae Infection]',
'Chronic Disease Prevention',
'Chronic Fatigue Syndrome (CFS)',
'Chronic Kidney Disease (CKD)',
'Chronic Obstructive Pulmonary Disease (COPD)',
'Chronic Wasting Disease (CWD)',
'Ciguatera Fish Poisoning',
'Ciguatoxin',
'CJD, Classic (Classic Creutzfeldt-Jakob Disease)',
'CKD (Chronic Kidney Disease)',
'CKD (Kidney Disease)',
'Classic Creutzfeldt-Jakob Disease (CJD, Classic)',
'Clonorchiasis',
'Clonorchis Infection [Clonorchiasis]',
'Clostridium botulinim Infection',
'Clostridium difficile Infection',
'Clostridium perfringens infection',
'Clostridium tetani Infection',
'Clotting Disorders',
'CMV (Cytomegalovirus Infection)',
'Coal Workers Pneumoconioses',
'Coccidioidomycosis',
'Cold, Common',
'Colorado Tick Fever (CTF)',
'Colorectal (Colon) Cancer',
'Colorectal Cancer Control Program (CRCCP)',
'Colorectal Cancer and Genetics',
'Common Cold',
'Concussion',
'Congenital Hearing Loss',
'Conjunctivitis',
'Cooley\'s Anemia',
'COPD (Chronic Obstructive Pulmonary Disease)',
'Corynebacterium diphtheriae Infection',
'Cough and Cold Medicines',
'Coxiella burnetii Infection',
'CRE (Carbapenem-resistant Enterobacteriaceae)',
'Creutzfeldt-Jakob Disease, Classic',
'Crimean-Congo hemorrhagic fever (CCHF) [Nairovirus Infection]',
'CRKP (Carbapenem resistant Klebsiella pneumonia )',
'Crohn’s Disease',
'Cronobacter Infection',
'Cryptococcosis, C. gattii.',
'Cryptococcosis, C. neoformans',
'Cryptosporidiosis',
'Cryptosporidium Infection [Cryptosporidiosis]',
'CTF (Colorado Tick Fever)',
'CWD (Chronic Wasting Disease)',
'Cyclospora Infection [Cyclosporiasis]',
'Cyclosporiasis',
'Cysticercosis',
'Cystoisospora Infection [Cystoisosporiasis]',
'Cystoisosporiasis',
'Cytomegalovirus Infection (CMV)',
'DBA (Diamond Blackfan Anemia)',
'Death, Leading Causes of Death in Males',
'Deep Vein Thrombosis (DVT)',
'Dengue Fever (DF)',
'Dengue Hemorrhagic Fever (DHF)',
'Dermatophyte Infection',
'Developmental Disabilities',
'DF (Dengue Fever)',
'DHF (Dengue Hemorrhagic Fever)',
'Diabetes',
'Diamond Blackfan Anemia (DBA)',
'Dientamoeba fragilis Infection',
'Diet and Nutrition',
'Diphtheria [Corynebacterium diphtheriae Infection]',
'Diphtheria Vaccination',
'Diphyllobothriasis',
'Diphyllobothrium Infection [Diphyllobothriasis]',
'Dipylidium Infection',
'Dirofilariasis (Dog Heartworm)',
'Division of Public Health Systems and Workforce Development (DPHSWD)',
'Division of Public Health Systems and Workforce Development (DPHSWD)',
'Dog Bites',
'Dog Flea Tapeworm',
'Dog Heartworm [Dirofilaria]',
'Dogs, Infections from',
'Down Syndrome [Trisomy 21]',
'DPHSWD (Division of Public Health Systems and Workforce Development)',
'Dracunculiasis',
'Drug Resistance',
'DVT (Deep Vein Thrombosis)',
'Dwarf Tapeworm [Hymenolepis Infection]',
'E. coli Infection [Escherichia coli Infection]',
'Ear Infection [Otitis Media]',
'Early Hearing Detection and Intervention (EHDI)',
'Eastern Equine Encephalitis (EEE)',
'Ebola Virus Disease (EVD)',
'EBV Infection (Epstein-Barr Virus Infection)',
'Echinococcosis',
'EEE (Eastern Equine Encephalitis)',
'EHDI (Early Hearing Detection and Intervention)',
'Ehrlichiosis, Human',
'Elephantiasis',
'Emerging Infectious Diseases',
'Endophthalmitis, Fungal',
'Entamoeba histolytica infection',
'Enteric Diseases from Animals',
'Enterobius vermicularis Infection',
'Enterovirus D68',
'Enterovirus Infections (Non-Polio)',
'Epidemic Typhus',
'Epilepsy',
'Epstein-Barr Virus Infection (EBV Infection)',
'Ergonomic and Musculoskeletal Disorders',
'Escherichia coli Infection',
'Esophageal Candidiasis',
'EV-D68',
'EVD (Ebola Virus Disease)',
'Exserohilum rostratum (Other Pathogenic Fungi)',
'Extensively Drug-Resistant TB (XDR TB)',
'Extreme Cold [Hypothermia]',
'Extreme Heat [Hyperthermia]',
'x',
'Falls from Elevation',
'Falls, Older Adults',
'Family Health',
'Family Health History',
'Family Health History and Breast and Ovarian Cancer',
'Farm Animals, Infections from',
'Farm Worker Injuries',
'Fasciitis, Necrotizing',
'Fasciola Infection [Fascioliasis]',
'Fascioliasis',
'Fasciolopsiasis',
'Fasciolopsis Infection [Fasciolopsiasis]',
'Fetal Alcohol Spectrum Disorder',
'FETP',
'FETP (Field Epidemiology Training Program)',
'Fibromyalgia',
'Field Epidemiology Training Program (FETP)',
'Fifth Disease [Parvovirus B19 Infection]',
'Filariasis, Lymphatic',
'Fireworks Injuries',
'Fish and Amphibians, Infections from',
'Flavorings-Related Lung Disease',
'Flu',
'Flu and Cancer',
'Flu Vaccination',
'Flu, Pandemic',
'Flu, Seasonal',
'Folliculitis',
'Food Poisoning',
'Food-Related Diseases',
'Clostridium perfringens infection',
'shigella Infection [Shigellosis]',
'Clostridium perfringens infection',
'Foodborne Illness',
'Fragile X Syndrome (FXS)',
'Francisella tularensis Infection',
'Fungal diseases [Mycotic diseases]',
'C. gattii cryptococcosis',
'C. neoformans cryptococcosis',
'Candida Infection [Candidiasis]',
'Histoplasma capsulatum Infection [Histoplasmosis]',
'Aspergillus Infection [Aspergillosis]',
'Blastomycosis [Blastomyces dermatitidis  Infection]',
'Blastomycosis [Blastomyces dermatitidis infection]',
'Fungal Eye Infections',
'Histoplasmosis [Histoplasma capsulatum Infection]',
'Mucormycosis',
'Pneumocystis pneumonia (PCP) [Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii) ]',
'Ringworm [Dermatophyte Infection]',
'sporotrichosis',
'sporotrichosis [Sporothrix schenckii infection]',
'Valley Fever [Coccidioidomycosis]',
'Fungal Eye Infections',
'Fungal Meningitis',
'Fungal Pneumonia',
'FXS (Fragile X Syndrome)',
'GAE  (Acanthamoe (Granulomatous Amebic Encephalitis (Acanthamoeba))',
'GAE (Granulomatous amebic encephalitis)',
'GAS (Group A Strep Infection)',
'Gastrointestinal Diseases from Animals [Zoonotic enteric diseases]',
'GBS (Group B Strep Infection)',
'GBS and Menactra Meningococcal Vaccine',
'GDDER (Global Disease Detection and Emergency Response)',
'Genetics and Colorectal Cancer',
'Genetics and Heart Disease',
'Genetics and Mental Health',
'Genetics and Obesity',
'Genetics and Skin Cancer',
'Genetics and Stroke',
'Genital Candidiasis (VVC) [Vulvovaginal Candidiasis]',
'Genital Herpes [Herpes Simplex Virus Infection]',
'Genital Warts',
'German Measles (Rubella Virus)',
'Giardia Infection [Giardiasis]',
'Giardiasis',
'Glanders [Burkholderia mallei]',
'Global Disease Detection and Emergency Response (GDDER)',
'Global Health Security',
'Global Measles Elimination',
'Gnathostoma Infection',
'Gnathostomiasis [Gnathostoma Infection]',
'Gonorrhea [Neisseria gonorrhoeae Infection]',
'Gout',
'Granulomatous amebic encephalitis (GAE)',
'Granulomatous Amebic Encephalitis (Acanthamoeba) (GAE  (Acanthamoe)',
'Group A Strep Infection (GAS) [Group A Streptococcal Infection]',
'Group A Streptococcal Infection',
'Group B Strep Infection (GBS) [Group B Streptococcal Infection]',
'Group B Streptococcal Infection',
'Guillain-Barré Syndrome and Menactra Meningococcal Vaccine',
'Guinea Worm Disease [Dracunculiasis]',
'Gynecologic Cancers',
'Cervical Cancer',
'Ovarian Cancer',
'Uterine Cancer',
'Vaginal and Vulvar Cancers',
'H3N2v influenza',
'H5N1',
'Haemophilus influenzae Infection (including Hib Infection)',
'Haemophilus influenzae Serotype b',
'Hand, Foot, and Mouth Disease (HFMD)',
'Hansen\'s Disease',
'Hantavirus Pulmonary Syndrome (HPS)',
'Hazardous Drug Exposures in Healthcare',
'Head Lice [Pediculus humanus capitis]',
'Health Disparities in Cancer',
'Health Disparities in HIV/AIDS, Viral Hepatitis, STDs, and TB',
'Health Security',
'Healthcare Associated Infections',
'surgical site infection (SSI)',
'Healthy Pets, Healthy People',
'Healthy Weight',
'Hearing Loss in Children',
'Hearing, Early Detection & Intervention',
'Heart Disease [Cardiovascular Health]',
'Heart Disease and Genetics',
'Heat Stress',
'Hemochromatosis',
'Hemoglobinopathies',
'Hemophilia',
'Hemophilia Treatment Centers (HTC)',
'Hemorrhagic Fevers, Viral',
'Hendra Virus Disease (HeV Infection)',
'Hepatitis A Vaccination',
'Hepatitis B Vaccination',
'Hepatitis, Viral',
'Hereditary Bleeding Disorders',
'Herpes B virus',
'Herpes Simplex Virus Infection',
'Herpes Zoster',
'Herpes Zoster Vaccination',
'Herpes, Genital',
'Herpesvirus B',
'Herpesvirus simiae',
'Heterophyes Infection [Heterophyiasis]',
'Heterophyiasis',
'HeV Infection (Hendra Virus Disease)',
'HFMD (Hand, Foot, and Mouth Disease)',
'Hib Infection [Haemophilus influenzae Serotype b]',
'Hib Vaccine (Haemophilus influenzae Serotype b Vaccination)',
'High Blood Pressure',
'Histoplasma capsulatum Infection [Histoplasmosis]',
'Histoplasmosis',
'HIV/AIDS',
'HIV/AIDS and STDs',
'Hookworm, Human [Ancylostoma duodenale Infection, Necator americanus Infection]',
'Hookworm, Zoonotic',
'Horses, Infections from',
'Hot Tub Rash [Pseudomonas dermatitis Infection]',
'HPIV (Human Parainfluenza Viruses)',
'HPS (Hantavirus Pulmonary Syndrome)',
'HPV Infection (Human Papillomavirus Infection)',
'HPV Vaccination (Human Papillomavirus Vaccination)',
'HPV-Associated Cancers',
'HTC (Hemophilia Treatment Centers)',
'Human Ehrlichiosis',
'Human Hookworm [Ancylostoma duodenale Infection, Necator americanus Infection]',
'Human Immunodeficiency Virus',
'Human Papillomavirus Infection (HPV Infection)',
'Human Papillomavirus Vaccination (HPV Vaccination)',
'Human Parainfluenza Viruses (HPIV)',
'Hymenolepis Infection',
'Hypertension',
'Hyperthermia',
'Hypothermia',
'IBD (Inflammatory Bowel Disease)',
'IMMPaCt (International Micronutrient Malnutrition Prevention and Control Program)',
'Impetigo',
'including Hib Infection (Haemophilus influenzae Infection)',
'Infectious Mononucleosis',
'Infertility',
'Inflammatory Bowel Disease (IBD)',
'Influenza',
'H1N1 Flu',
'People at High Risk',
'seasonal Flu',
'swine Influenza',
'Influenza and Cancer',
'Influenza in Pigs',
'Influenza Vaccination',
'Influenza, Avian',
'Influenza, Pandemic',
'Injury, Healthy Swimming and Recreational Water',
'International Micronutrient Malnutrition Prevention & Control Program (IMMPaCt)',
'Intestinal Amebae Infection, Nonpathogenic',
'Invasive Candidiasis',
'Iron Overload [Hemochromatosis]',
'Iron Storage Disease',
'Isospora Infection [Isosporiasis]',
'Japanese Encephalitis (JE)',
'Japanese Encephalitis (JE) Vaccination',
'Jaundice',
'JE (Japanese Encephalitis)',
'JE (Japanese Encephalitis) Vaccination',
'K. pneumoniae (Klebsiella pneumoniae)',
'Kala-Azar',
'Kawasaki Disease (KD)',
'Kawasaki Syndrome',
'KD (Kawasaki Disease)',
'Keratitis, Acanthamoeba',
'Keratitis, Fungal',
'Kernicterus',
'KFD (Kyasanur Forest disease)',
'Kidney Disease (CKD)',
'Klebsiella pneumoniae (K. pneumoniae)',
'Kyasanur Forest disease (KFD)',
'La Crosse Encephalitis (LAC)',
'La Crosse Encephalitis virus (LACV)',
'LAC (La Crosse Encephalitis)',
'LACV (La Crosse Encephalitis virus)',
'Lassa Fever',
'Latex Allergies',
'LCM (Lymphocytic Choriomeningitis)',
'Lead Poisoning',
'Legionellosis',
'Legionnaires Disease [Legionellosis]',
'Leishmania Infection [Leishmaniasis]',
'Leishmaniasis',
'Leprosy',
'Leptospira Infection [Leptospirosis]',
'Leptospirosis',
'Lice',
'Lice, Body',
'Lice, Head',
'Lice, Pubic',
'Listeria Infection [Listeriosis]',
'Listeriosis',
'Liver Disease and Hepatitis',
'Loa loa Infection',
'Lockjaw',
'Lockjaw Vaccination',
'Loiasis [Loa loa Infection]',
'Lou Gehrig\'s Disease',
'LUHF (Lujo Hemorrhagic Fever)',
'Lujo Hemorrhagic Fever (LUHF)',
'Lung Cancer',
'Lupus (SLE) [Systemic lupus erythematosus]',
'Lyme Disease [Borrelia burgdorferi Infection]',
'Lymphatic Filariasis',
'Lymphedema',
'Lymphocytic Choriomeningitis (LCM)',
'MAC (Mycobacterium avium Complex)',
'Mad Cow Disease (BSE)',
'Malaria',
'Marburg Hemorrhagic Fever',
'Marine Toxins',
'MD (Muscular Dystrophy)',
'MDR TB (Multidrug-Resistant TB)',
'Measles',
'Measles Vaccination',
'Melioidosis [Burkholderia pseudomallei Infection]',
'Men\'s Health',
'Meningitis',
'Meningococcal Disease',
'Meningococcal Vaccination',
'Mental Health',
'Mental Health and Genetics',
'Mental Retardation',
'MERS-CoV (Middle East Respiratory Syndrome Coronavirus)',
'Methicillin Resistant Staphylococcus aureus',
'Microcephaly',
'Micronutrient Malnutrition',
'Microsporidia Infection',
'Middle East Respiratory Syndrome Coronavirus (MERS-CoV)',
'MMR Vaccination',
'Molluscum Contagiosum',
'Monkey B virus',
'Monkeypox',
'Monkeypox Vaccination',
'Mononucleosis, Infectious',
'Motor Vehicle Injuries',
'Mouse and Rat Control',
'MRSA [Methicillin Resistant Staphylococcus aureus]',
'Mucormycosis',
'Mucus',
'Multidrug-Resistant TB (MDR TB)',
'Multiple organ dysfunction syndrome',
'Mumps',
'Mumps Vaccination',
'Muscular Dystrophy (MD)',
'Musculoskeletal Disorders',
'Mycobacterium abscessus Infection',
'Mycobacterium avium Complex (MAC)',
'Mycobacterium tuberculosis Infection',
'Mycoplasma pneumoniae Infection',
'Mycotic diseases',
'Myelomeningocele',
'Myiasis',
'Naegleria Infection [Primary Amebic Meningoencephalitis (PAM)]',
'Nairovirus Infection',
'National Amyotrophic Lateral Sclerosis (ALS) Registry',
'Necrotizing Fasciitis',
'Neglected Tropical Diseases (NTD)',
'Neisseria gonorrhoeae Infection',
'Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii) ',
'Neurocysticercosis',
'Newborn Hearing',
'Newborn Jaundice [Kernicterus]',
'Nocardia asteroides Infection',
'Nocardiosis [Nocardia asteroides Infection]',
'Non-Polio Enterovirus Infections',
'Nonpathogenic (Harmless) Intestinal Protozoa',
'Norovirus Infection',
'Norwalk-like Viruses (NLV)',
'NTD (Neglected Tropical Diseases)',
'Nutrition',
'OA (Osteoarthritis)',
'Obesity and Genetics',
'Obesity and Overweight',
'Obesity and Overweight, Childhood',
'Occupational Cancers',
'Occupational Skin Conditions',
'Occupational Stress',
'OHF (Omsk hemorrhagic fever)',
'Omsk hemorrhagic fever (OHF)',
'Onchocerciasis',
'Opisthorchis Infection',
'Oral Cancer',
'Orf Virus Infection',
'Oropharyngeal Candidiasis',
'Oroya fever',
'Osteoarthritis (OA)',
'Otitis Media',
'Outbreaks',
'Ovarian and Breast Cancer and Family Health History',
'Ovarian Cancer',
'Overweight and Obesity',
'Overweight and Obesity, Childhood',
'PAD (Peripheral Arterial Disease)',
'Pandemic Flu',
'Paragonimiasis',
'Paragonimus Infection [Paragonimiasis]',
'Parainfluenza',
'Parasitic Diseases',
'Parvovirus B19 Infection',
'PCP (Pneumocystis pneumonia)',
'PCV (Pneumococcal Conjugate Vaccine)',
'PE (Pulmonary Embolism)',
'Pedestrian Injury',
'Pediculus humanus capitis',
'Pediculus humanus corporis',
'Pelvic Inflammatory Disease (PID)',
'Peripheral Arterial Disease (PAD)',
'Peripheral Arterial Insufficiency',
'Peripheral Arterial Occlusive Disease',
'Peripheral Vascular Disease',
'Pertussis (Whooping Cough)',
'Pertussis (Whooping Cough) Vaccination',
'Pet-Related Diseases',
'Phthiriasis',
'PID (Pelvic Inflammatory Disease)',
'Pigs, Influenza in',
'Pink Eye [Conjunctivitis]',
'Pinworm Infection [Enterobius vermicularis Infection]',
'Plague [Yersinia pestis Infection]',
'Pneumococcal Conjugate Vaccine (PCV)',
'Pneumococcal Disease',
'Pneumococcal Polysaccharide Vaccine (PPV)',
'Pneumoconioses, Coal Workers',
'Pneumocystis carinii Pneumonia (PCP) Infection',
'Pneumocystis pneumonia (PCP) [Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii) ]',
'Pneumonia',
'Polio Infection [Poliomyelitis Infection]',
'Polio Vaccination [Poliomyelitis Vaccination]',
'Poliomyelitis Infection',
'Poliomyelitis Vaccination',
'Pontiac Fever',
'Powassan (POW) virus',
'Poxvirus Infections',
'PPV (Pneumococcal Polysaccharide Vaccine)',
'Pregnancy',
'Primary Amebic Meningoencephalitis (PAM)',
'Prion Diseases (TSEs) [Transmissible spongiform encephalopathies]',
'Prostate Cancer',
'Pseudomonas dermatitis Infection',
'Psittacosis',
'Psoriasis',
'Pubic Lice [Phthiriasis]',
'Pulmonary Embolism (PE)',
'Pulmonary Hypertension',
'Q Fever [Coxiella burnetii Infection]',
'RA (Rheumatoid Arthritis)',
'Rabies',
'Rabies Vaccination',
'Raccoon Roundworm Infection [Baylisascaris Infection]',
'Rat-Bite Fever (RBF) [Streptobacillus moniliformis Infection]',
'RBF (Rat-Bite Fever)',
'Recalled Vaccines',
'Recreational Water Illness (RWI)',
'Reptiles, Infections from',
'Respiratory Syncytial Virus Infection (RSV)',
'Rheumatoid Arthritis (RA)',
'Rickettsia rickettsii Infection',
'Rickettsia, Spotted Fever Group',
'Rickettsial Diseases',
'Rift Valley Fever (RVF)',
'Ringworm [Dermatophyte Infection]',
'Ringworm from Animals',
'River Blindness [Onchocerciasis]',
'RMSF (Rocky Mountain Spotted Fever)',
'Rocky Mountain Spotted Fever (RMSF) [Rickettsia rickettsii Infection]',
'Rodent Control',
'Rodents',
'Rodents, Diseases from',
'Rotavirus Infection',
'Rotavirus Vaccination',
'RSV (Respiratory Syncytial Virus Infection)',
'Rubella (German Measles) Vaccination',
'Rubeola',
'Runny Nose',
'RVF (Rift Valley Fever)',
'RWI (Recreational Water Illness)',
'salmonella typhi Infection',
'salmonella Infection [Salmonellosis]',
'salmonella Infection from Animals',
'salmonellosis',
'salt',
'sappinia diploidea and Sappinia pedata',
'sappinia Infection [Sappinia diploidea and Sappinia pedata]',
'sARS [Severe Acute Respiratory Syndrome]',
'scabies',
'scarlet Fever',
'schistosoma Infection',
'schistosomiasis [Schistosoma Infection]',
'seasonal Flu',
'sepsis [Septicemia]',
'septic shock',
'septicemia',
'severe Acute Respiratory Syndrome',
'sexually Transmitted Disease Surveillance Reports',
'sexually Transmitted Diseases (STDs)',
'Bacterial Vaginosis (BV)',
'Chlamydia [Chlamydia trachomatis Disease]',
'Genital Herpes [Herpes Simplex Virus Infection]',
'Gonorrhea [Neisseria gonorrhoeae Infection]',
'Human Papillomavirus Infection (HPV Infection)',
'Pelvic Inflammatory Disease (PID)',
'syphilis [Treponema pallidum Infection]',
'Trichomoniasis [Trichomonas Infection]',
'sFGR (Spotted Fever Group Rickettsia)',
'shigella Infection [Shigellosis]',
'shigellosis',
'shingles [Varicella Zoster Virus (VZV)]',
'shingles Vaccination',
'sickle Cell Disease',
'sIDS (Sudden Infant Death Syndrome)',
'sinus Infection [Sinusitus]',
'sinusitus',
'skin Cancer',
'skin Cancer and Genetics',
'skin Conditions, Occupational',
'sLE (Lupus)',
'sleep and Sleep Disorders',
'sleeping Sickness [African Trypanosomiasis]',
'smallpox [Variola Major and Variola Minor]',
'smallpox Vaccination',
'smoking and Tobacco Use',
'sodium',
'soil Transmitted Helminths',
'sore Mouth Infection [Orf Virus Infection]',
'sore Throat',
'southern Tick-Associated Rash Illness (STARI)',
'spina Bifida [Myelomeningocele]',
'spirillum minus Infection',
'sporothrix schenckii infection',
'sporotrichosis [Sporothrix schenckii infection]',
'spotted Fever Group Rickettsia (SFGR)',
'staph',
'staphylococcus aureus Infection',
'sTARI (Southern Tick-Associated Rash Illness)',
'sTDs (Sexually Transmitted Diseases)',
'sTDs and HIV/AIDS',
'strep Infection, Group A',
'strep Infection, Group B',
'strep Throat',
'streptobacillus moniliformis Infection',
'streptococcus pneumoniae Infection',
'stress, Occupational',
'stroke',
'stroke and Genetics',
'strongyloidiasis',
'sudden Infant Death Syndrome (SIDS)',
'surveillance Reports, Sexually Transmitted Disease',
'swimmer\'s Itch [Cercarial Dermatitis]',
'swimming-related Illness',
'swine Influenza',
'symptom Relief for Upper Respiratory Infections',
'syphilis [Treponema pallidum Infection]',
'systemic lupus erythematosus',
'Taenia Infection',
'Tapeworm Infection [Taenia Infection]',
'Tapeworm, Dog and Cat Flea [Dipylidium Infection]',
'TB (Tuberculosis)',
'TB (Tuberculosis) Vaccination',
'TB and HIV Coinfection',
'TB and the African-American Communtiy',
'TB Data & Statistics',
'TB Education and Training Network',
'TB in African-Americans',
'TB Surveillance Reports',
'TB Testing & Diagnosis',
'TBI (Traumatic Brain Injury)',
'Testicular Cancer',
'Tetanus (Lockjaw) Infection',
'Tetanus (Lockjaw) Vaccination',
'Tetanus Disease [Clostridium tetani Infection]',
'Thalassemia',
'Thoracic Aortic Aneurysm',
'Throat, Sore',
'Throat, Strep',
'Thrombophilia',
'Thrombosis',
'Thrush [Oropharyngeal Candidiasis]',
'Tickborne Diseases',
'Ticks',
'Anaplasmosis, Human',
'Babesiosis [Babesia Infection]',
'Ehrlichiosis, Human',
'Lyme Disease [Borrelia burgdorferi Infection]',
'Powassan (POW) virus',
'Rocky Mountain Spotted Fever (RMSF) [Rickettsia rickettsii Infection]',
'southern Tick-Associated Rash Illness (STARI)',
'Tularemia [Francisella tularensis Infection]',
'Tinea',
'Tobacco Use, Smoking and',
'Tourette Syndrome  (TS)',
'Toxocara Infection',
'Toxocariasis [Toxocara Infection]',
'Toxoplasma Infection',
'Toxoplasmosis [Toxoplasma Infection]',
'Trachoma Infection',
'Transmissible spongiform encephalopathies',
'Traumatic Brain Injury (TBI)',
'Traumatic Occupational Injuries',
'Trench fever [Bartonella quintana Infection]',
'Treponema pallidum Infection',
'Trichinellosis (Trichinosis)',
'Trichomonas Infection',
'Trichomoniasis [Trichomonas Infection]',
'Trichuriasis',
'Trisomy 21',
'Trypanosoma cruzi Infection',
'Trypanosomiasis, African',
'TS (Tourette Syndrome )',
'TSEs (Prion Diseases)',
'Tuberculosis (TB) [Mycobacterium tuberculosis Infection]',
'Tuberculosis (TB) Vaccination',
'Tuberculosis and HIV Coinfection',
'Tuberculosis Skin Test',
'Tuberculosis Training',
'Tuberculosis Vaccine (BCG)',
'Tularemia [Francisella tularensis Infection]',
'Typhoid Fever [Salmonella typhi Infection]',
'Typhoid Fever Vaccination',
'Typhus Fevers',
'Ulcerative Colitis',
'Undulant Fever',
'Unexplained Respiratory Disease Outbreaks (URDO)',
'Universal Newborn Hearing Screening',
'Upper Respiratory Infection Symptom Relief',
'URDO (Unexplained Respiratory Disease Outbreaks)',
'Uterine Cancer',
'Vaccination',
'Vaccination and Pregnancy',
'Vaccination, American Indian and Alaska Native',
'Vaccine Adverse Event Reporting System (VAERS)',
'Vaccine Information Statements (VIS)',
'Vaccine Ingredients',
'Vaccine Management System (VACMAN)',
'Vaccine Recalls, Questions About',
'Vaccine Safety',
'Vaccine Safety (Emergency Preparedness)',
'Vaccine Safety Concerns',
'Vaccine Safety for Measles, Mumps, Rubella, Varicella (MMRV)',
'Vaccine Safety, Intussusception and Rotavirus Vaccine',
'Vaccine Side Effects',
'Vaccine Tracking System (VTrckS)',
'Vaccine-Preventable Diseases and Specific Vaccines',
'Vaccines',
'Vaccines and Sudden Infant Death Syndrome (SIDS)',
'Vaccines and Thimerosal (Mercury)',
'Vaccines for Children Program',
'Vaccines, Testing and Monitoring',
'VACMAN (Vaccine Management System)',
'VAERS (Vaccine Adverse Event Reporting System)',
'Vaginal and Vulvar Cancers',
'Vaginal Candidiasis',
'Valley Fever [Coccidioidomycosis]',
'Vancomycin-Intermediate/Resistant Staphylococcus aureus Infections [VISA/VRSA]',
'Vancomycin-resistant Enterococci Infection (VRE)',
'VAP (Ventilator-associated pneumonia)',
'Variant Creutzfeldt-Jakob Disease (vCJD)',
'Varicella Disease',
'Varicella Vaccination',
'Varicella Zoster Virus (VZV)',
'Varicella-Zoster Virus Infection',
'Variola Major and Variola Minor',
'vCJD (Variant Creutzfeldt-Jakob Disease)',
'Vehicle Safety',
'Venezuela',
'Venomous Snakes',
'Venomous Spiders',
'Venous Thromboembolism (VTE)',
'Ventilator-associated pneumonia (VAP)',
'Vermiculite',
'verruga peruana',
'Vessel Sanitation and Health',
'Veterinary Safety and Health',
'Veterinary Students, Epidemiology Elective Program for',
'VFC Program [Vaccines for Children Program]',
'VHF (Viral Hemorrhagic Fevers)',
'Vibration',
'Vibrio cholerae Infection',
'Vibrio Illness [Vibriosis]',
'Vibriosis',
'Video',
'Vietnam',
'Violence',
'Violence, Occupational',
'Viral Hemorrhagic Fevers (VHF)',
'Alkhurma hemorrhagic fever (AHF)',
'Chapare Hemorrhagic Fever (CHHF)',
'Crimean-Congo hemorrhagic fever (CCHF) [Nairovirus Infection]',
'Ebola Virus Disease (EVD)',
'Hantavirus Pulmonary Syndrome (HPS)',
'Kyasanur Forest disease (KFD)',
'Lassa Fever',
'Lujo Hemorrhagic Fever (LUHF)',
'Marburg Hemorrhagic Fever',
'Omsk hemorrhagic fever (OHF)',
'Rift Valley Fever (RVF)',
'Viral Hepatitis',
'Viral Meningitis [Aseptic Meningitis]',
'Virtual Platform Initiative (VPI)',
'VIS (Vaccine Information Statements)',
'VISA/VRSA',
'Vision and Mission, CDC',
'Vision Health Initiative',
'Vision Impairment',
'Visitors Center',
'Vital and Health Statistics Reports (Rainbow Series)',
'Vital Records',
'Vital Signs',
'Vital Signs Town Hall Conferences',
'VitalStats',
'Vitamins',
'Volcanoes',
'Von Willebrand Disease',
'VPD Surveillance Manual',
'VPI (Virtual Platform Initiative)',
'VRE (Vancomycin-resistant Enterococci Infection)',
'VTE (Venous Thromboembolism)',
'VTrckS (Vaccine Tracking System)',
'Vulnerable',
'Vulvovaginal Candidiasis',
'VVC (Genital Candidiasis)',
'VWD [Von Willebrand Disease]',
'VX',
'VZV (Varicella Zoster Virus)',
'Weight, Healthy',
'West Nile Virus Infection (WNV Infection)',
'Whipworm Infection [Trichuriasis]',
'Whitmore\'s Disease',
'Whooping Cough',
'Whooping Cough (Pertussis) Vaccination',
'Wildlife, Infections from',
'Winter Storms',
'WNV Infection (West Nile Virus Infection)',
'Women\'s Bleeding Disorders',
'Women\'s Health',
'XDR TB (Extensively Drug-Resistant TB)',
'Xenotropic Murine Leukemia Virus-related Virus Infection',
'XMRV Infection [Xenotropic Murine Leukemia Virus-related Virus Infection]',
'Yeast Infection',
'Yellow Fever',
'Yellow Fever Vaccination',
'Yersinia enterocolitica Infection',
'Yersinia pestis Infection',
'Yersiniosis [Yersinia enterocolitica Infection]',
'Zika Virus Infection',
'Zoonotic Diseases from Animals',
'Zoonotic enteric diseases',
'Zoonotic Hookworm',
'Zoster',
'Zygomycosis '
],
  orgs: [
    'Homo sapiens',
    'Arabidopsis thaliana',
    'Homo neanderthalensis',
    'Proboscidea',
    'Bacillus',
    'reptiles',
    'Agathis montana',
    'Mus musacris'
  ],
  exp: [
    'Expression profiling by array',
    'Expression profiling by high throughput sequencing',
    'Expression profiling by RT-PCR',
    'Genome binding/occupancy profiling by high throughput sequencing',
    'Genome variation profiling by array',
    'Genome variation profiling by genome tiling array',
    'Genome variation profiling by SNP array',
    'Methylation profiling by high throughput sequencing',
    'Non-coding RNA profiling by array',
    'Non-coding RNA profiling by high throughput sequencing',
    'Protein profiling by protein array'
  ],
  dummyResult: [{ "GSE_Acc": "5725236846", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [expression array]", "GSM_count": 1, "last_update_date": "1/29/2017", "Summary": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.", "Overall_Design": "Focused intermediate database" },
    { "GSE_Acc": "4894698285", "Title": "Morphological", "GSM_count": 2, "last_update_date": "1/31/2017", "Summary": "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", "Overall_Design": "Advanced logistical flexibility" },
    { "GSE_Acc": "7648248743", "Title": "Chordoma Cell Lines Characterization", "GSM_count": 3, "last_update_date": "1/22/2017", "Summary": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.", "Overall_Design": "Right-sized eco-centric groupware" },
    { "GSE_Acc": "8143393143", "Title": "and transcriptomic characterization of heterogeneity in chordoma cells", "GSM_count": 4, "last_update_date": "1/29/2017", "Summary": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.", "Overall_Design": "Open-architected discrete toolset" },
    { "GSE_Acc": "2114572641", "Title": "Morphological", "GSM_count": 5, "last_update_date": "1/19/2017", "Summary": "Curabitur in libero ut massa volutpat convallis.", "Overall_Design": "Public-key composite moderator" },
    { "GSE_Acc": "0043198694", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [expression array]", "GSM_count": 6, "last_update_date": "1/9/2017", "Summary": "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.", "Overall_Design": "Progressive asymmetric challenge" },
    { "GSE_Acc": "9859819912", "Title": "Chordoma_32k_1Mb", "GSM_count": 7, "last_update_date": "1/9/2017", "Summary": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.", "Overall_Design": "Configurable web-enabled matrix" },
    { "GSE_Acc": "7236298654", "Title": "Chordoma Cell Lines Characterization", "GSM_count": 8, "last_update_date": "1/21/2017", "Summary": "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.", "Overall_Design": "Cloned systemic complexity" },
    { "GSE_Acc": "3633794824", "Title": "Chordoma ATAC-Seq", "GSM_count": 9, "last_update_date": "1/20/2017", "Summary": "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.", "Overall_Design": "Robust leading edge monitoring" },
    { "GSE_Acc": "4920222297", "Title": "Morphological", "GSM_count": 10, "last_update_date": "1/8/2017", "Summary": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.", "Overall_Design": "Total fault-tolerant workforce" },
    { "GSE_Acc": "4480698957", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [expression array]", "GSM_count": 11, "last_update_date": "1/27/2017", "Summary": "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.", "Overall_Design": "Managed 24/7 benchmark" },
    { "GSE_Acc": "9029032650", "Title": "Morphological", "GSM_count": 12, "last_update_date": "1/21/2017", "Summary": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.", "Overall_Design": "Enterprise-wide zero defect website" },
    { "GSE_Acc": "8501920916", "Title": "Chordoma ATAC-Seq", "GSM_count": 13, "last_update_date": "1/18/2017", "Summary": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.", "Overall_Design": "Multi-channelled motivating monitoring" },
    { "GSE_Acc": "9428301817", "Title": "Affymetrix SNP 6.0 array data for chordoma samples", "GSM_count": 14, "last_update_date": "2/2/2017", "Summary": "Suspendisse potenti. Cras in purus eu magna vulputate luctus.", "Overall_Design": "Assimilated executive system engine" },
    { "GSE_Acc": "1897582765", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [SNP array]", "GSM_count": 15, "last_update_date": "1/9/2017", "Summary": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.", "Overall_Design": "Public-key real-time archive" },
    { "GSE_Acc": "5650660522", "Title": "Affect of Interferon Gamma on Chordoma Cells", "GSM_count": 16, "last_update_date": "1/21/2017", "Summary": "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.", "Overall_Design": "Robust bandwidth-monitored frame" },
    { "GSE_Acc": "7515264233", "Title": "Affymetrix SNP 6.0 array data for chordoma samples", "GSM_count": 17, "last_update_date": "1/15/2017", "Summary": "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.", "Overall_Design": "Ergonomic bandwidth-monitored contingency" },
    { "GSE_Acc": "9450227136", "Title": "T (Brachyury) gene duplication confers major susceptibility to familial chordoma", "GSM_count": 18, "last_update_date": "1/10/2017", "Summary": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.", "Overall_Design": "Multi-layered well-modulated info-mediaries" },
    { "GSE_Acc": "3787415831", "Title": "Chordoma Cell Lines Characterization", "GSM_count": 19, "last_update_date": "1/15/2017", "Summary": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", "Overall_Design": "Profound exuding parallelism" },
    { "GSE_Acc": "0390676454", "Title": "Chordoma Cell Lines Characterization", "GSM_count": 20, "last_update_date": "1/14/2017", "Summary": "Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.", "Overall_Design": "Intuitive impactful encoding" },
    { "GSE_Acc": "5249702368", "Title": "Chordoma ATAC-Seq", "GSM_count": 21, "last_update_date": "1/10/2017", "Summary": "Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.", "Overall_Design": "Multi-lateral client-driven Graphical User Interface" },
    { "GSE_Acc": "8632090593", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [SNP array]", "GSM_count": 22, "last_update_date": "1/25/2017", "Summary": "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.", "Overall_Design": "Cloned responsive projection" },
    { "GSE_Acc": "0737549939", "Title": "Chordoma_32k_1Mb", "GSM_count": 23, "last_update_date": "1/14/2017", "Summary": "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.", "Overall_Design": "Advanced asymmetric project" },
    { "GSE_Acc": "9413472106", "Title": "Chordoma_32k_1Mb", "GSM_count": 24, "last_update_date": "1/30/2017", "Summary": "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.", "Overall_Design": "Multi-lateral context-sensitive alliance" },
    { "GSE_Acc": "4570038883", "Title": "and transcriptomic characterization of heterogeneity in chordoma cells", "GSM_count": 25, "last_update_date": "2/1/2017", "Summary": "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.", "Overall_Design": "Multi-tiered bifurcated utilisation" },
    { "GSE_Acc": "7520163202", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [SNP array]", "GSM_count": 26, "last_update_date": "1/19/2017", "Summary": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.", "Overall_Design": "Networked directional workforce" },
    { "GSE_Acc": "5333750645", "Title": "Affymetrix SNP 6.0 array data for chordoma samples", "GSM_count": 27, "last_update_date": "1/5/2017", "Summary": "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.", "Overall_Design": "Sharable optimal moderator" },
    { "GSE_Acc": "2740255764", "Title": "Integrated miRNA-mRNA analysis revealing the potential roles of miRNAs in chordomas", "GSM_count": 28, "last_update_date": "2/1/2017", "Summary": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.", "Overall_Design": "Robust attitude-oriented hub" },
    { "GSE_Acc": "3065100398", "Title": "Morphological", "GSM_count": 29, "last_update_date": "1/12/2017", "Summary": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.", "Overall_Design": "Triple-buffered didactic superstructure" },
    { "GSE_Acc": "7348832881", "Title": "T (Brachyury) gene duplication confers major susceptibility to familial chordoma", "GSM_count": 30, "last_update_date": "1/15/2017", "Summary": "Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.", "Overall_Design": "Fully-configurable static interface" },
    { "GSE_Acc": "3975054565", "Title": "Chordoma Cell Lines Characterization", "GSM_count": 31, "last_update_date": "1/6/2017", "Summary": "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.", "Overall_Design": "Seamless object-oriented framework" },
    { "GSE_Acc": "3432060785", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [SNP array]", "GSM_count": 32, "last_update_date": "1/21/2017", "Summary": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.", "Overall_Design": "Realigned context-sensitive success" },
    { "GSE_Acc": "7240355179", "Title": "Chordoma Cell Lines Characterization", "GSM_count": 33, "last_update_date": "1/5/2017", "Summary": "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.", "Overall_Design": "Front-line eco-centric Graphical User Interface" },
    { "GSE_Acc": "7138028768", "Title": "Affect of Interferon Gamma on Chordoma Cells", "GSM_count": 34, "last_update_date": "1/5/2017", "Summary": "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "Overall_Design": "Realigned value-added data-warehouse" },
    { "GSE_Acc": "8066215460", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [expression array]", "GSM_count": 35, "last_update_date": "2/1/2017", "Summary": "In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.", "Overall_Design": "Enhanced mobile firmware" },
    { "GSE_Acc": "1743281617", "Title": "T (Brachyury) gene duplication confers major susceptibility to familial chordoma", "GSM_count": 36, "last_update_date": "1/26/2017", "Summary": "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.", "Overall_Design": "Multi-layered client-driven Graphical User Interface" },
    { "GSE_Acc": "7390539216", "Title": "Chordoma_32k_1Mb", "GSM_count": 37, "last_update_date": "1/13/2017", "Summary": "Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.", "Overall_Design": "Ameliorated neutral infrastructure" },
    { "GSE_Acc": "8151030879", "Title": "Affect of Interferon Gamma on Chordoma Cells", "GSM_count": 38, "last_update_date": "1/7/2017", "Summary": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.", "Overall_Design": "Profit-focused demand-driven moratorium" },
    { "GSE_Acc": "4224828529", "Title": "genomic", "GSM_count": 39, "last_update_date": "1/30/2017", "Summary": "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.", "Overall_Design": "Organic demand-driven projection" },
    { "GSE_Acc": "8653009191", "Title": "Heterogeneous genetic profiles in soft tissue myoepitheliomas", "GSM_count": 40, "last_update_date": "1/25/2017", "Summary": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.", "Overall_Design": "Versatile full-range hub" },
    { "GSE_Acc": "3186270049", "Title": "A novel chordoma xenograft allows in vivo drug testing and reveals the importance of NF-kB signaling in chordoma biology [expression array]", "GSM_count": 41, "last_update_date": "1/5/2017", "Summary": "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.", "Overall_Design": "Adaptive logistical utilisation" },
    { "GSE_Acc": "1372401393", "Title": "Affect of Interferon Gamma on Chordoma Cells", "GSM_count": 42, "last_update_date": "1/12/2017", "Summary": "Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.", "Overall_Design": "Advanced intangible circuit" },
    { "GSE_Acc": "17786477410", "Title": "Chordoma ATAC-Seq", "GSM_count": 43, "last_update_date": "1/17/2017", "Summary": "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", "Overall_Design": "Progressive dedicated system engine" },
    { "GSE_Acc": "0086269526", "Title": "Morphological", "GSM_count": 44, "last_update_date": "1/29/2017", "Summary": "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.", "Overall_Design": "Quality-focused content-based artificial intelligence" },
    { "GSE_Acc": "1315699737", "Title": "Heterogeneous genetic profiles in soft tissue myoepitheliomas", "GSM_count": 45, "last_update_date": "1/14/2017", "Summary": "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.", "Overall_Design": "Secured 4th generation strategy" },
    { "GSE_Acc": "3171708728", "Title": "Heterogeneous genetic profiles in soft tissue myoepitheliomas", "GSM_count": 46, "last_update_date": "1/29/2017", "Summary": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.", "Overall_Design": "Intuitive executive support" },
    { "GSE_Acc": "5441097671", "Title": "Chordoma ATAC-Seq", "GSM_count": 47, "last_update_date": "1/14/2017", "Summary": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.", "Overall_Design": "Re-contextualized bi-directional intranet" },
    { "GSE_Acc": "3131868406", "Title": "Heterogeneous genetic profiles in soft tissue myoepitheliomas", "GSM_count": 48, "last_update_date": "1/9/2017", "Summary": "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.", "Overall_Design": "Adaptive encompassing algorithm" },
    { "GSE_Acc": "2711231232", "Title": "Morphological", "GSM_count": 49, "last_update_date": "1/31/2017", "Summary": "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.", "Overall_Design": "Implemented disintermediate definition" },
    { "GSE_Acc": "7305398764", "Title": "genomic", "GSM_count": 50, "last_update_date": "1/10/2017", "Summary": "In hac habitasse platea dictumst.", "Overall_Design": "Face to face intermediate methodology" }]
}
